### ISSUE TITLE
[Request] Toggle death drops

### ISSUE THREAD

**Issue by PsychoLynx** [mcmonkey4eva/Sentinel#1]
Yo! Since replacing Sentry with Sentinel there's been one Sentry option that I've been missing, namely the ability to control whether or not NPC-killed mobs have drops (exp, rotten flesh etc). I would love to see this in Sentinel.

**Comment by mcmonkey4eva** [comment]
In addition to controlling *whether* they have drops *at all*, definitely need a neat way to control what exactly does drop. I'm not sure how to set that up though - any ideas?

**Comment by PsychoLynx** [comment]
I'm honestly not sure if changing mob drops _in a general sense _ needs to be in the scope of this plugin as there are plenty of plugins targetting it already (e.g. https://www.spigotmc.org/resources/custommobdrops.9302/). I suppose if you wanted, you could add some sort of optional config file, but again, I just feel that's not in the scope of this plugin. Also, I don't recall how Sentry does this, but IMHO NPC-killed players should definitely drop their stuff regardless (to work with deathchests etc.)

**Comment by CorporalBruno** [comment]
/sentinel drops

opens chest that you can place items into from your inventory.

saves it as drops on close.
