### ISSUE TITLE
Ranged Combat in chase when out of range of melee

### ISSUE THREAD

**Issue by CorporalBruno** [mcmonkey4eva/Sentinel#10]
Ranged Combat in chase when out of range of melee

switch to ranged weapon if in the inventory or whatever and engage the targets until out of chase range or back in melee range. then switch to best weapon.

basically always use the most intelligent weapon for the current moment in the battle.

**Comment by mcmonkey4eva** [comment]
So, an optional mode that grabs the most-relevant weapon for a situation, specifically most helpful when chase is disabled.
Can probably be still functional with chase on for both ranged/close combat to cause the NPC to attack while chasing :D

**Comment by mcmonkey4eva** [comment]
Added to Sentinel 0.7!

`/sentinel autoswitch` to enable this. Give an NPC a bow and sword and watch them accurately choose which to use :D
