### ISSUE TITLE
Little Suggestions 

### ISSUE THREAD

**Issue by xXMrGXx** [mcmonkey4eva/Sentinel#100]
1. Add an custom Bow attackrate
10 Ticks attackrate is optimal for swordmen npcs, but way to fast for archers.
Since you added support for let the npc's autoswitch their items, i would like to have an custom bow attackrate

2. Explain the Sentinel "Squad" feature in your Readme file :)

**Comment by mcmonkey4eva** [comment]
Squad feature is basically: If one NPC in a squad is attacked, all other NPCs in that squad will react and help out.

**Comment by mcmonkey4eva** [comment]
New build contains a command/functionality modification.\
You can now do:
```
/sentinel attackrate 10
/sentinel attackrate 30 ranged
```

To set a separate swords vs. ranged weapon rate!

**Comment by xXMrGXx** [comment]
Will your new build work on mc 1.10 or only 1.11?

**Comment by mcmonkey4eva** [comment]
1.11
