### ISSUE TITLE
Factions support?

### ISSUE THREAD

**Issue by keough99** [mcmonkey4eva/Sentinel#101]
Is there factions support? If there is not can it please be added like it was in the original sentry plugin
And maybe a way to group npcs so you can mass edit npcs without having to select the npc edit it then move on to the next.

**Comment by Jabelpeeps** [comment]
@keough99 While you are waiting for mcmonkey to implement this, you could always try my re-write of Sentry:- https://github.com/Jabelpeeps/Sentries which is attempting to maintain the old functions, before adding new ones.  There is a link to the builds on my CI server in the ReadMe.  Let me know how you get on.

**Comment by mcmonkey4eva** [comment]
Faction targets are now available to Factions servers in the latest dev build (#74)
Simply `/sentinel addtarget factions:BADDIE_FACTION`
Also supports ignores!

Oh and please do reply telling me how it works for you, and any additional features you'd like to see!
