### ISSUE TITLE
Problem with using sentinel

### ISSUE THREAD

**Issue by dutejsn** [mcmonkey4eva/Sentinel#102]
Whenever I try to set a npc's trait to Sentinel it throws an error and the trait cannot be added.

26.11 21:09:07 [Server] WARN at java.lang.Thread.run(Unknown Source)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
26.11 21:09:07 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
26.11 21:09:07 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
26.11 21:09:07 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
26.11 21:09:07 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
26.11 21:09:07 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
26.11 21:09:07 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
26.11 21:09:07 [Server] WARN at java.lang.reflect.Method.invoke(Unknown Source)
26.11 21:09:07 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
26.11 21:09:07 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
26.11 21:09:07 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
26.11 21:09:07 [Server] WARN at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
26.11 21:09:07 [Server] WARN at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:384)
26.11 21:09:07 [Server] WARN at org.mcmonkey.sentinel.SentinelTarget.<clinit>(SentinelTarget.java:10)
26.11 21:09:07 [Server] WARN java.lang.NoSuchFieldError: DONKEY

the server is Spigot 1.10.2, what is the problem?

**Comment by mcmonkey4eva** [comment]
Latest builds expect 1.11's new features.
Which don't exist in 1.10
Grab an older build from https://wiki.citizensnpcs.co/Versions#Sentinel_Versions

**Comment by dutejsn** [comment]
Thank you!
