### ISSUE TITLE
Factions integration?

### ISSUE THREAD

**Issue by Ditronian** [mcmonkey4eva/Sentinel#105]
Is this actually working? 

The documentation on how to do this seems to be fairly lacking, but I'd assume it would just be /sentinel addtarget factions:[FactionName].

Needless to say, that command throws an invalid target and there doesn't seem to be a Factions Type listed ingame, despite the documentation saying the following.

Sentinel integrations with a few external plugins, including:

-     Vault, for permission group targets! (Use group:GROUP_HERE)
-     Towny, for town targets! (Use towny:TOWN_HERE)
-     Factions, for faction targets! (Use factions:FACTION_HERE)_

As far as I can tell the vault groups are the only one of the three listed ingame as a valid type.

Thanks, 

Ditronian

**Comment by mcmonkey4eva** [comment]
It should work, on latest dev builds (1.11)
Can you post a full server startup log, if they don't seem to work for you?

**Comment by Ditronian** [comment]
Ah I found a newer dev build that reads the addtargets command like you say.

That being said, once the faction is loaded into the npc's target list and is approached by a member of that faction, the console begins spewing errors like there's no tomorrow.  The NPC also does not attack.

Here's a log of server startup, and login by a target faction member next to the npc.  Error Spam in log starts at line 805.

[latest.txt](https://github.com/mcmonkey4eva/Sentinel/files/629294/latest.txt)

Thanks

**Comment by mcmonkey4eva** [comment]
It looks like you targeted a faction that contains a player that... doesn't exist, or doesn't have a modern UUID?
Either way, I "handled" this error, in the newest dev (`#80`) build by just ignoring any erroneous data Factions gives and continue to look through what data is validly available.

With any luck, that's sufficient to fix it. If it gives more errors or functions oddly, lemme know and I'll look closer.

**Comment by Ditronian** [comment]
It's a 20 man faction, so its possible there's a name change in there that hasn't logged in yet?

Either way the plugin works beautifully now, we greatly appreciate your work!

Ditronian

**Comment by mcmonkey4eva** [comment]
Something like that, yeah.
And good to hear that!
