### ISSUE TITLE
New Attack Patterns

### ISSUE THREAD

**Issue by xBiscuit** [mcmonkey4eva/Sentinel#108]
On my old server I had a warlock and a witch...
For the warlock it used to be an enderpearl which it threw to make things jump
Warlock 2, which i used for my witch used a skull, and it threw skulls towards enemies.
This is from the official page:

> ENDER_PEARL 	Warlock I	The lowest tier of the 667th Warlocks. These sorcerers imbue their magic crystals with the kinetic power of the endermen, flinging their targets high into the air. Remember: it's not the fall that kills you, it's the sudden stop at the end.

> SKULL_ITEM	Warlock II 	The mid-range warlock shoots black explosive wither skulls at the enemy.

Please add them back :) Thanks

**Comment by xBiscuit** [comment]
Also, is there any place we can get dev builds?

**Comment by mcmonkey4eva** [comment]
First link on the readme

**Comment by mcmonkey4eva** [comment]
Added the first attack ^

**Comment by mcmonkey4eva** [comment]
Wither skull attacks are a fair bit over powered - they break blocks apparently. I've added it to Sentinel, but made it config-optional.

**Comment by xBiscuit** [comment]
Oh I just made a simple skript that replaces any wither skull on hit with a fake explosion

**Comment by xBiscuit** [comment]
Oh wait, If replace the original wither skull then the damage doesn't get blocked by your plugin. ;c
Is it possible for you to cancel the wither skull on hit, but create a fake explosion that they _are still immune to?_ 
Skript has a "fake explosion" effect.. Maybe this can be of any use to you?
https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/effects/EffExplosion.java

**Comment by mcmonkey4eva** [comment]
If you replace the attack with something else, then making it not deal damage is your own problem.

Also, last I heard, Skript is a dead project. Might a recommend a more modern scripting engine for spigot/minecraft, _Denizen_? https://wiki.citizensnpcs.co/Denizen
it's fully capable of making wither skulls not do block damage if that was your goal, or alternately protecting NPCs from damage, or whatever else you might need.

**Comment by xBiscuit** [comment]
Ok thanks! Also for the warlock, the enemies get pushed up although I can't see the enderpearl being thrown. It doesn't have to be on the spot, at least if theres an enderpearl flying in its direction it looks realistic :P And if its possible, since the enderpearl doesn't do damage, can you base the "damage" stat on the enderpearl to the jump strength? Thanks anyways :)

**Comment by mcmonkey4eva** [comment]
`can you base the "damage" stat on the enderpearl` oh, yeah, that'll work! Was wondering what to base that off

**Comment by xBiscuit** [comment]
Also my last post was a bit confusing, when i said this

>  Also for the warlock, the enemies get pushed up although I can't see the enderpearl being thrown. It doesn't have to be on the spot, at least if theres an enderpearl flying in its direction it looks realistic

But this is what i'm talking about: http://sendvid.com/fwe1xww1

**Comment by mcmonkey4eva** [comment]
Maybe the NPC is so cool he doesn't even need to so much as look at the target to do that?
:P 
I fixed the problems in latest build.

**Comment by xBiscuit** [comment]
It's not that much about the entity looking at the target, its just that it isn' throwing anything ;p

**Comment by xBiscuit** [comment]
Thanks for the improvements! :D
