### ISSUE TITLE
Going crazy with snowballs

### ISSUE THREAD

**Issue by xBiscuit** [mcmonkey4eva/Sentinel#109]
I used to have a citizen that bombarded people with snowballs... But now the maximum attack speed is 10 ticks for ranged :C Any way this can be increased?
And the old sentry allowed you to throw eggs too? Is that possible?
And finally I have a bug. Sometimes a sentinel targeting a player in the air will go crazy and start throwing snowballs everywhere... When theres nothing around.
Thanks for this awesome plugin anyways :)

**Comment by mcmonkey4eva** [comment]
There's a command to change ranged or general attack speed.
`/sentinel attackrate RATE ['ranged'] - Changes the rate at which the NPC attacks, in ticks. Either ranged or close modes.`
Unless you mean you want that _lower_ than 10, in which case, edit the Sentinel config file - https://github.com/mcmonkey4eva/Sentinel/blob/master/src/main/resources/config.yml#L56
Eggs, can be added.
As for the final point, can you record a video of that bug behavior?

**Comment by xBiscuit** [comment]
Oh I thought that meant how long it took to find new targets... Ill record a vid later.. Also, how can you add the egg?

**Comment by xBiscuit** [comment]
Also I set

> update rate: 2
but it still says invalid rate number: number out of range when i try lower than attackrate 10

**Comment by mcmonkey4eva** [comment]
Eggs added as weapon ^

**Comment by mcmonkey4eva** [comment]
Also, fixed the lower-than-10 hardlimit ^

**Comment by mcmonkey4eva** [comment]
That leaves `And finally I have a bug. Sometimes a sentinel targeting a player in the air will go crazy and start throwing snowballs everywhere... When theres nothing around.` waiting on you to get a video.

**Comment by xBiscuit** [comment]
Wow your support is great.. Thanks for that :D Ill try to catch it going crazy one sec ;p

**Comment by xBiscuit** [comment]
Ok here is the video:
http://sendvid.com/o6tyv64c
In this example, the ice mage is targeting the endermites. I kill them to give him a helping hand, and then he has no target. Since I'm in gamemode c he doesn't target me. He then follows me near the cactus and starts going crazy.. side to side, targeting nothing. Thanks for all your help!

**Comment by mcmonkey4eva** [comment]
It almost looks like the NPC is targetting itself. Which... _shouldn't_ happen.
Just in case, I pushed an extra tough system to further prevent that. Can you replicate this on dev build `#86`?

**Comment by xBiscuit** [comment]
I was not able to replicate it! Thanks! Although with the wither skull attack, is it possible to make the citizen immune to its own explosion?

**Comment by mcmonkey4eva** [comment]
NPCs should be protected from themselves in the latest dev version.

**Comment by xBiscuit** [comment]
Thanks for all of this!
