### ISSUE TITLE
Sentinel NPCs respawning inside blocks

### ISSUE THREAD

**Issue by Ditronian** [mcmonkey4eva/Sentinel#110]
Me again, sorry :/

We've begun rolling out sentinel on mass for our server, and have noticed an all too common problem of NPCs partially/fully inside blocks after respawning at their spawnpoints.  Observing the process from a fresh NPC, it seems the Sentinel respawn always seems to place the NPC directly on a corner/edge of the block they were standing on when performing the /sentinel spawnpoint command.

Once partially inside a block, block clipping no longer becomes an issue for them and it is extremely easy for them to be pushed further inside whatever object they're partly in.  If they do manage to spawn all the way outside of a block (very rare for NPCs indoors), it otherwise seems impossible for them to clip their way inside of a block.

In the meanwhile Denizen's spawn command seems to be much more precise, so we have taken to a script to solve the problem.

Thanks,

Ditronian

**Comment by mcmonkey4eva** [comment]
Oh woops, didn't think of that case.
Fixed!
