### ISSUE TITLE
Sentinel tracking system

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#113]
Hello,

As you can see on this video, we have noticed that the way the sentinel targets the player is designed in such a way it makes its movement very un-realistic, highly predictable, and thus makes it really easy to defeat the sentinel.

https://streamable.com/78c2

In fact, we have noticed that the sentinel always directs itself to the previous "known" location of the player. That means it doesn't actually follow the player, it just goes where the player was a few moments before. The result is a sentinel that mimics the player's movement, which makes it very predictable for the player, but also with a delay compared to the player's movement, which allows the player to "outplay" the sentinel whatever way he wants.

On the following video, you can see an example of the numerous downsides of this : the player attacks the sentinel, and then hides immediately litterally one block away frome the sight of the sentinel, but since the sentinel is programmed to just go where the player attacked it, it then doesn't know where the player went, even if it's just beside it.

https://streamable.com/ysg6

I think a way to solve this would be to check the player's position relatively to the sentinel every X ticks, in an asynchrone way. Also, it should not be able to lose sight of the player so easily, so you probably should add something to detects where the player is (and the way to reach him) even when he hides, if it's very near.

In other games as well as in Sentry, I believe they made a system that allowed the NPC to constantly follows the player while he was in sight of the NPC, and the following continues for a few seconds (like, 5 or 10) after the sentinel loses sight of the player. It's a little "cheaty" in a way, because that means the NPC knows where the player goes even if it loses sight from him for a few seconds, but it sure is far better than a completely dumb NPC which gets outplayed by a 1 block movement from the player.

**Comment by mcmonkey4eva** [comment]
In the new build, they chase a bit closer (Relies on Citizens a bit more for that), and will remember targets for a bit (5 seconds by default, config'able) (excluding when they have better available targets, which will be attacked instead of a remembered target)

**Comment by Blamo27** [comment]
@mcmonkey4eva Thank you, it's a lot better now. There still is a little bit of weirdness with the way the NPC's head moves, but that's not really important. The system is now fine.
