### ISSUE TITLE
Problem with sentinel create

### ISSUE THREAD

**Issue by Pacorus** [mcmonkey4eva/Sentinel#114]
hi i use Spigot 1.10 And if I want to create a Sentinel comes this error message what should I do?

20:11:02 CONSOLE: WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
20:11:02 CONSOLE: WARN]: at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:414)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
20:11:02 CONSOLE: WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:11:02 CONSOLE: WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:11:02 CONSOLE: WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:11:02 CONSOLE: WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
20:11:02 CONSOLE: WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
20:11:02 CONSOLE: WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
20:11:02 CONSOLE: WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
20:11:02 CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
20:11:02 CONSOLE: WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
20:11:02 CONSOLE: WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
20:11:02 CONSOLE: WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
20:11:02 CONSOLE: WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by mcmonkey4eva** [comment]
@Pacorus latest Sentinel is built for 1.11, so either update to that or use an older Sentinel build from https://wiki.citizensnpcs.co/Versions#Sentinel_Versions
