### ISSUE TITLE
Archer NPCs don't look at targets

### ISSUE THREAD

**Issue by Goetheus** [mcmonkey4eva/Sentinel#115]
Hi McMonkey!

I noticed that NPCs with a bow shoot targets without look at them!
I maybe forget to add a parameter or something... But they simply don't move (x/y/z/yaw or pitch).

**Versions :**
Minecraft Spigot 1.10.2
Citizens 2.0.21, build 1437
Sentinel 0.8, build 69

Thank you for help!
And keep going :)

**Comment by mcmonkey4eva** [comment]
Citizens 2.0.21 issue with NPC rotation, I'm pretty sure. Sentinel has its rotation code in place, but that relies on the Citizens part of it working :/

**Comment by mcmonkey4eva** [comment]
Should be functional in latest versions of Citizens+Sentinel+Spigot!
