### ISSUE TITLE
Add citizens as faction members?

### ISSUE THREAD

**Issue by CurtainHumper** [mcmonkey4eva/Sentinel#116]
I would like to create the following scenery: there are two factions, both with normal players and with NPC's. But can I add NPC's to a faction? Because when both factions attack each other, (I have added the factions correctly as enemies) the rival NPC's only attack the real players. Can I simply add the NPC's to their faction, or do I have to create two seperate 'squads', one for each faction?

**Comment by mcmonkey4eva** [comment]
Adding NPCs directly to a faction would require... Factions add support for that.

I've done what I can for supporting Factions from my own end. Using squads would be a good way to accomplish what you need I think, yes.

**Comment by CurtainHumper** [comment]
Thanks a lot! 
One more thing:
I would like to give my guards swords for melee fights, and bows for ranged fights.
If I am in equip-mode, I can only give them one weapon. (e.g. when I give a bow/arrows to a NPC holding a sword, it drops the sword). When I go in their inventory and try to simply place a second weapon in there, it just disappears.
I have tried it with autoswitch-mode on and off.

**Comment by mcmonkey4eva** [comment]
Make sure you're not accidentally giving the weapon to an armor slot or something, and also that you have permission to give items, etc. etc.
