### ISSUE TITLE
An error is flooding my console

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#119]
Hello,

An error is flooding my console, can you fix this ?

Thanks.

>1.12 21:49:04 [Server] ERROR [Citizens] An exception occurred while the trait sentinel was spawning for NPC ID 6,565.
21.12 21:49:04 [Server] WARN java.lang.ClassCastException: net.citizensnpcs.nms.v1_11_R1.entity.nonliving.WitherSkullController$WitherSkullNPC cannot be cast to org.bukkit.entity.LivingEntity
21.12 21:49:04 [Server] WARN at org.mcmonkey.sentinel.SentinelTrait.getLivingEntity(SentinelTrait.java:1206)
21.12 21:49:04 [Server] WARN at org.mcmonkey.sentinel.SentinelTrait.setHealth(SentinelTrait.java:1786)
21.12 21:49:04 [Server] WARN at org.mcmonkey.sentinel.SentinelTrait.onSpawn(SentinelTrait.java:1655)
21.12 21:49:04 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:244)
21.12 21:49:04 [Server] WARN at net.citizensnpcs.EventListen.spawn(EventListen.java:572)
21.12 21:49:04 [Server] WARN at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:549)
21.12 21:49:04 [Server] WARN at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:139)
21.12 21:49:04 [Server] WARN at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
21.12 21:49:04 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21.12 21:49:04 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
21.12 21:49:04 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
21.12 21:49:04 [Server] WARN at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
21.12 21:49:04 [Server] WARN at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
21.12 21:49:04 [Server] WARN at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.Chunk.loadNearby(Chunk.java:910)
21.12 21:49:04 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:53)
21.12 21:49:04 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
21.12 21:49:04 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
21.12 21:49:04 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
21.12 21:49:04 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.World.getChunkAt(World.java:329)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.World.getChunkAtWorldCoords(World.java:325)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.World.getType(World.java:806)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.TileEntityChest.b(TileEntityChest.java:186)
21.12 21:49:04 [Server] WARN at net.minecraft.server.v1_11_R1.TileEntityChest.a(TileEntityChest.java:168)

**Comment by mcmonkey4eva** [comment]
Did you somehow manage to try to apply Sentinel to a wither skull typed NPC?

**Comment by Blamo27** [comment]
What do you mean by wither skull typed NPC ? A wither skeleton sentinel ? A wither sentinel ?
A normal sentinel with a wither skeleton skull equipped ?

Anyway, in all of theses case the answer is yes : we have such sentinels, since we imported them from Sentry. I suppose they are in conlict with a feature you're developping ? How can we fix this ?

**Comment by mcmonkey4eva** [comment]
None of those. Specifically a Wither Skull NPC. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html#WITHER_SKULL
You somehow (accidentally?) typed an NPC to that and Sentinel doesn't know how to make a skull entity do combat, Sentinel only functions with living typed NPCs currently. (EG player, cow, pig, skeleton, yadda yadda... things that move and do stuff on their own if they are spawned outside of Citizens)

**Comment by Blamo27** [comment]
I can't see how we could have made such an NPC, even accidentally, especially since we didn't create any new NPC in the last two months (and the error only appeared recently). Furtheremore, we noticed that the error was only present when we had the new "protected" option set to true in the configuration (the one we asked for in another post). If it is set to false, no error anymore. So I really don't think it's related to a wither skull NPC.

**Comment by mcmonkey4eva** [comment]
The update from 1.10 to 1.11 in some cases caused entity types to be read wrong - perhaps that happened to you?
That error message is fairly clear that there exists a WitherSkull NPC Sentinel...

**Comment by Blamo27** [comment]
Well, there doesn't seem to be this kind of NPC in our Citizens saves.yml (we searched via ctrl+f). Also, the error doesn't happen we set the protected option to false in the config file, even if we're on 1.11...

**Comment by Blamo27** [comment]
Mmh, I dug a little deeper and, just to try out some things, and I deleted the only WitherBoss NPC we had. Turns out it was it, but that's weird, it's just a regular witherboss NPC. Since this NPC wasn't so important to us, we juste removed it. If you want to have a look at its configuration for bug-fixing purposes, here it is :
http://pastebin.com/HJRMCHzq

**Comment by mcmonkey4eva** [comment]
Are you sure it was accurately spawning in-game as a wither boss?

**Comment by Blamo27** [comment]
It was before, but in game it indeed didn't appear. Again, I can't really understand why.

**Comment by mcmonkey4eva** [comment]
Correct entitytype is WITHER. 1.10 saved some entities under wrong names that aren't compatible with the 1.11 name set.

**Comment by Blamo27** [comment]
Oh, got it. Thanks !
