### ISSUE TITLE
NPC bug when player is beyond chase range

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#120]
Hello,

As you can see on the video below, a sentinel that goes outside of its Chase Range starts to get buggy and is stuck constantly (as long as the player is in sight, at least) in a loop of movement. 

https://streamable.com/gv5xa

On this video, the NPC has a range of 20, and a chase range of 25. When the player gets outside of the 25 chase range, the NPC doesn't know what to do. I think if the player gets outside of the chase range, the NPC should simply just return to its original position (in a roleplay way, that would imply it "gave up" on chasing the player and decided to "go home"). That would make much more sense.

**Comment by mcmonkey4eva** [comment]
Should be better in new version?

**Comment by Blamo27** [comment]
NPC doesn't detect you at all when chase range is anything higher than 0. However, we tried putting it at 0 so it attacks and follows the player, than put it at 30, and when the player left the chase range of 30 it indeed went back home. So the only problem here seems to be an absence of detection when chase range is higher than 0.

**Comment by mcmonkey4eva** [comment]
My bad, I let a typo creep in to that commit... /now/ it'll work? :P

**Comment by Blamo27** [comment]
Seems to work now. We will do more tests in the future, but that specific issue appears to be fixed. Thanks !
