### ISSUE TITLE
NPC attacks slowly when player is beyond range

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#121]
Hello, 

As you can see on the video below, when a player is within the range of a sentinel, the said sentinel correctly hits the player with normal attack rate. But, when the players goes beyond the range limit, though below the CHASE range limit, the sentinel indeed continues to chase the player, but only attacks it at a very, very low attackrate (one attack every 15 seconds, roughly).

https://streamable.com/l0n2z

At the beggining, the sentinel attacks regularly, but as soon as the player leaves the "detection" range (but, he is still within the chase range), the NPC takes forever to attack (it still attacks though, just at a very, very slow rate). That unfortunately makes the chase range pretty much useless...

**Comment by mcmonkey4eva** [comment]
Could be related to #120 ?

**Comment by Blamo27** [comment]
Actually it changed a bit, but not for the better ! Now, when the NPC is beyond detection range (but bellow chase range), it follows and sticks to the player for, like 10 seconds, and then gives up and returns home, even though the player did not move from the chase range !

**Comment by mcmonkey4eva** [comment]
What happens if you set range at least as high as chase range?

**Comment by Blamo27** [comment]
Well obviously the issue will disappear if we do that, since it's precisely happening only BETWEEN the detection range limit and the chase range limit ! If the two are equals, then there's no "bug zone", but chase range doesn't serve any real purpose in that case (we would want that the NPC actually follows the player beyond the detection range, up to the chase range limit, if the player tries to run away)

**Comment by mcmonkey4eva** [comment]
I don't know why that would ever happen. `range` is only ever handled in terms of distance between NPC and target. `chaseRange` is handled both in terms of that and between NPC-Guard-Zone and target.
It makes no sense for the `range` value to matter at all relative to the guard zone...

**Comment by Blamo27** [comment]
It's not really that, the main issue is that the chase range doesn't serve any purpose right now : when the player gets beyond the range limit, and is still IN the chase range limit (so, he is only in the chase range area, not in the detection range area anymore), the sentinel stops attacking the player and simply follows him, sticks to it, without even attacking it now : 

https://streamable.com/kjtqy

After a few seconds, the NPC gives up and goes back home.

**Comment by mcmonkey4eva** [comment]
That's visibly attempting to chase, but failing to actually attack - it's perfectly consistent with not having line of sight. I think there's something at play beyond the range limits here...

**Comment by Blamo27** [comment]
Okay, so it is indeed a bug, right ? Is there a way to fix it on our side, or will you be able to make a build for that...?

**Comment by Blamo27** [comment]
@mcmonkey4eva Sooo... are you working on it...? We still can't make our NPCs work because of this...!

**Comment by mcmonkey4eva** [comment]
Sorry for the excess delays, Ima crack down on this particular bug now. See if I can replicate things and get whatever's going on fixed!

**Comment by mcmonkey4eva** [comment]
The NPCs are fairly stupid in their movement... but this bug is now fixed in latest dev build! Build 99+ http://ci.citizensnpcs.co/job/Sentinel/

**Comment by Blamo27** [comment]
This issue seems to be fixed with the latest build. Thanks !
