### ISSUE TITLE
Add shield support

### ISSUE THREAD

**Issue by xBiscuit** [mcmonkey4eva/Sentinel#123]
When an NPC has auto switch on, It can switch weapons normally, however it never switches to its wand. Just wondering, could you add support for shield switching?

**Comment by mcmonkey4eva** [comment]
its "`wand`"?

**Comment by mcmonkey4eva** [comment]
If you want shields, show your support in https://github.com/mcmonkey4eva/Sentinel/issues/70

**Comment by xBiscuit** [comment]
I don't know how shields turned into wands... But yea ill go there.
