### ISSUE TITLE
Sentinels do not follow properly

### ISSUE THREAD

**Issue by xBiscuit** [mcmonkey4eva/Sentinel#124]
Ive been seeing a wierd bug lately.. Usually sentinels follow the player better, but now it seems their AI is messed up. The sentinel in the video has guard on. It seems to get stuck on simple slopes, and I don't know if this is intented, but even when I turn on "/npc swim --true and /npc pathopt --avoid-water false, it doesn't like the water. Hope this can be fixed, thanks 🙂 
https://vid.me/29Qp

**Comment by xBiscuit** [comment]
It seems that instead of actually trying to find a path to them, they just try to get a tiny bit closer and end up lost.

**Comment by mcmonkey4eva** [comment]
That'd be a fault in Citizens - https://github.com/CitizensDev/Citizens2/issues

Sentinel does not control pathfinding internals such as water/swimming, or how to handle slopes, that's all in Citizens. Sentinel, as far as pathfinding, only tells them **where** to go.

**Comment by xBiscuit** [comment]
Do you also work on citizens?

**Comment by xBiscuit** [comment]
Hm, i also made a bug report on citizens.. maybe they are related... thanks 👍
