### ISSUE TITLE
Ability to remove specific target from 

### ISSUE THREAD

**Issue by Nutty101** [mcmonkey4eva/Sentinel#126]
I can add targets to Sentinel via SentinelTrait.addTarget(UUID). However, I cannot remove a single user. I have been using the method SentinelTrait.onDespawn() to clear the set but that removes all players.  Would you be able to add a method for removing a single target UUID?

```
SentinelTrait sent = npc.getTrait(SentinelTrait.class);
      if (sent.currentTargets.contains(player.getUniqueId()))
         sent.currentTargets.remove(player.getUniqueId());
```
will cause

```
[22:33:46 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:33:46 WARN]: Caused by: java.lang.IllegalAccessError: tried to access field
org.mcmonkey.sentinel.SentinelTrait.currentTargets from class {calling class}
```

**Comment by mcmonkey4eva** [comment]
I think you're building against one version of Sentinel but running a different one...? `currentTargets` is valid to modify.
Either way, you're using a UUID when you're meant to use a SentinelCurrentTarget. You can do:
```
        SentinelCurrentTarget target = new SentinelCurrentTarget();
        target.targetID = id;
        sentinel.currentTargets.remove(target);
```

**Comment by Nutty101** [comment]
Yup, exactly what it was. 0.6 on the server and didn't even catch that until now.  You nailed the issue 100% on that one. Need to make sure I put a check in for a min version for other servers.

Thanks again!
