### ISSUE TITLE
Drops - enchantments

### ISSUE THREAD

**Issue by jakubman1** [mcmonkey4eva/Sentinel#128]
When creating drops from NPCs, enchantments are not saved in config.. This causes dropping unenchanted items after first server reset..

**Comment by mcmonkey4eva** [comment]
If this happens, it would unfortunately be an issue with Citizens item persistence, not Sentinel itself.
Please report at https://github.com/CitizensDev/Citizens2/issues if this happens in the most recent dev builds of all relevant plugins and Spigot.
