### ISSUE TITLE
Sentinel does not come to you when entering server

### ISSUE THREAD

**Issue by MrKiller01** [mcmonkey4eva/Sentinel#129]
Hi, a very nice addition to those silly citizens.... although i noticed a little thing you might consider... I made succesfully with your examples an guard that protects me and follows me. I kinda mis the way weapons (more than 1) can be added, but i'm still in the try-out stage...so no hurry on this...
What i find remarkable is that the guard follows until i leave the server and from where i was, i will get back to spawn point through a plugin (https://www.spigotmc.org/resources/always-spawn-spawn-tp.10058/) but my buddy, Bob, the guard, is nowhere to be found until i'm close to the point where i left the server.
Is there a reason for that, or can we instruct the sentinel to walk towards me if i would reenter the server? automatically?

Thanks for this great plugin, so nice people enjoy making nice plugins....
Ps. latest logfile as to where you can find file versions etc...
[latest - copy.zip](https://github.com/mcmonkey4eva/Sentinel/files/743336/latest.-.copy.zip)

**Comment by mcmonkey4eva** [comment]
Should be fixed in dev build 101+ at http://ci.citizensnpcs.co/job/Sentinel/
Thanks for the report!

**Comment by MrKiller01** [comment]
No, THANK YOU! (-:
