### ISSUE TITLE
Groups:  Ability to add groups for targets

### ISSUE THREAD

**Issue by Nutty101** [mcmonkey4eva/Sentinel#13]
So we can get the NPC's to target players in perm groups.

**Comment by LoreCase** [comment]
There is also a issue with 1.9 nocheatplus, the player is unable to get hurt by melee attacks.
Finally, there is no EVENT: paremeter. Aka, EVENT:PVP  or EVENT:PVNPC .

**Comment by mcmonkey4eva** [comment]
@LoreCase For melee: Toggle the 'workaround damage' in your config. For the other one, please post a new issue.

**Comment by mcmonkey4eva** [comment]
Nevermind the new issue, I added event targets just now.
