### ISSUE TITLE
Player can´t defend an arrow of a NPC with a shield

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#130]
Hello. Nice Plugin, the most things work fine. I have one problem: I equiped an sentinel NPC with a bow and arrows. If he shoot to a player, the player can´t defense it with his shield like normaly. An armor doesn´t have the normal function against these arrows too. An armor reduce the damage of an sentinel with sword but not with a bow. The problem with armor ist not so important but in a fight you must can defend arrows with a shield...

enforce damage in config is false

**Comment by Firemonkey08** [comment]
Do you have an Idea what it could be? 

If found the methods tryAttack for bow and the getdamage, but where do you define the damage for the attack with bow? Didnt found it in the tryAttack.

**Comment by mcmonkey4eva** [comment]
Lines 248+ (`whenAttacksAreHappening`) control relevant logic.

It has to set damage manually via that event, rather than there being an option to set the damage of an arrow for some reason. Because of that, it makes sense for it to not properly account for all blocking and damage modifying effects :/ Probably the best way to make it work would realistically just be to replicate the shield logic or something... which is awkward

**Comment by Firemonkey08** [comment]
Ok. I have the problem, that i cannot handle your project. When I want to export it, I get only errors... Do you think, u could make a version, where the shields block the arrows?

**Comment by Firemonkey08** [comment]
I´m a beginner in bukkit coding, but I think it´s not so difficult it looks like. You modify the DamageModifier.BASE while checking DamageModifier.ARMOR. Now you have to modify the damage while checking DamageModifier.BLOCKING, DamageModifier.ABSORPTION and DamageModifier.RESISTANCE, too. All the Damageparameters are in these DamageModifers, the Base value also. So I think you have only to add up all Modifiers.

The normal damageeveentlogic seems to be:

```
HashMap<DamageModifier, Double> MODIFIERS = new HashMap<DamageModifier, Double>();

public final double getFinalDamage() {
	double damage = 0.0D;
	for (DamageModifier modifier : MODIFIERS) {
		damage += getDamage(modifier);
	}
	return damage;
}
```

To fill the MODIFIERS I would use:

```
for (DamageModifier modifier : EntityDamageEvent.DamageModifier.values()){
    	MODIFIERS.put(modifier, event.getDamage(modifier));
}
```
Does it help?

**Comment by mcmonkey4eva** [comment]
You wrote:
```java
for (DamageModifier modifier : EntityDamageEvent.DamageModifier.values()){
    	MODIFIERS.put(modifier, event.getDamage(modifier));
}
```
that's useless code (in a literal sense): It takes the damage and sets the damage to the damage.
It literally changes nothing. No effect is resultant.

Also, the SentinelTrait code that deals with armor values is for objects striking the NPC.
The code that handles arrows impacting players does not deal with any damage other base.
Which, in theory, is sufficient: any and all other damage modifiers still have their original values.

I'm going to debug/test an idea I have from that, though, which is to multiply the other damage modifier values by the relative damage scaling. Perhaps the other damage modifiers are still present, but are too weak compared to how the the Sentinel modifies base damage? Or something like that...

**Comment by mcmonkey4eva** [comment]
Yup, my idea worked nicely. It's been added to build 102, tell me how it goes!

**Comment by Firemonkey08** [comment]
First Test works fine. Blocking is correct and now the player-armor against arrows is correct, too. We will test it more on our server, but it looks very good until now. Thanks a lot :)
