### ISSUE TITLE
Killing NPC with bows

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#131]
So it appears that we can completely "outplay" sentinels simply by using a bow ! As you can see on this video, you simply have to stand outside of the detection range of the NPC and fire at it until it's dead. 

https://streamable.com/4ey8b

It would be nice to make it so the NPC tracks down any player shooting at it even if the said player is beyond the detection range, but below the maximum chase range. This way, it wouldn't be possible to just stand outside the detection range and kill the NPC with ranged attacks.

Also, as you can see, there is this issue (https://github.com/mcmonkey4eva/Sentinel/issues/98) appearing again, we still don't know why. When the NPC is standing still and not triggered by anything, it flies when hit. It only goes down when getting too far away from its base waypoint, meaning that if we don't put any waypoint, the NPC could fly forever as long as it isn't triggered by anything.

**Comment by Firemonkey08** [comment]
Hi Blamo,

you can enable the Fightback. Then he will run and fight against the player shooting him even the range is higher then the detection range. That works for me.

LG Firemonkey

**Comment by Blamo27** [comment]
Hi,

Fightback is enabled on this NPC, so I'm affraid it's not that easy...

**Comment by Firemonkey08** [comment]
When i shoot with bow and the detection range is minimal he is even coming. U are running 1.11?

**Comment by Blamo27** [comment]
Yes.

**Comment by Blamo27** [comment]
The things you said made me think about it and run some new tests. After extensive experimentation on every aspect of the sentinel, I found out what was wrong : it appears that if the sentinel target time is anything below 11, it doesn't react to ranged attacks from outside its detection range. The sentinels we have obviously had 10 as target time, so it was too low. 
So, it's fixed on our side, but I have a question about target time : is it in seconds, or in ticks ? And how does it work exactly ?

**Comment by mcmonkey4eva** [comment]
That uh... should be either 0, or above 10. any value above 0 but below 11 is erroneous. Why did you have it at 10? 0.0
it's in ticks. 10 is how rapidly the Sentinel system ticks by default. IE, 10 ticks = it's removed on the very first iteration, and the enemy is never chased.

I would recommend setting it to 0 unless you have reason to set it higher, in which case you should set it to like 200 (10 seconds) or other high values to give it a fair chance of actually bothering to chase enemies down.

Target time is how long it'll chase an enemy for before giving up.
IE, half a second (10 ticks) would be crazy low even if that wasn't considered erroneous.

**Comment by Blamo27** [comment]
Well, because I didn't know how it worked, I thought it was in seconds. Also, the transfer from sentry to sentinel set the target time of every NPC that was previously a sentry to 10, which is why it didn't work on any of our NPC.

Anyway, it is now more clear and easy to fix, so thank you.
