### ISSUE TITLE
Guarding an NPC?

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#134]
Is it possible, that an NPC guard an other NPC? Would be great that a higher ranked NPC gets his own guard.

**Comment by mcmonkey4eva** [comment]
That's... an interesting concept. I don't know if that falls under the category of reasonable usage...

**Comment by Firemonkey08** [comment]
I am searching something like this: https://www.spigotmc.org/resources/npc-groups.14399/ 
He wanted to defend a group leader, or defend anyone on the group.
But it's not so important.

**Comment by Firemonkey08** [comment]
I´m using now the Value Squad, this is what I wanted :)
