### ISSUE TITLE
Unknown entity [DONKEY]

### ISSUE THREAD

**Issue by Moderocky** [mcmonkey4eva/Sentinel#136]
On adding the trait (or creating NPC with the trait) I get the message unknown entity [Donkey]
I am running 1.10.2 spigot server, which is within the supported range.

I have tried every version on Spigot and most of the ones on Jenkins. All of them provide the same error. I have tried pairing with a different version of citizens but that is the only working one.

Error log (from restart):
http://pastebin.com/g19R3cGm

**Comment by mcmonkey4eva** [comment]
Check here: https://wiki.citizensnpcs.co/Versions#Sentinel_Versions
You want Sentinel build 69 for your outdated server

**Comment by Moderocky** [comment]
Much obliged. :)
