### ISSUE TITLE
Sentinel's not taking damage (error)

### ISSUE THREAD

**Issue by TheSodaPopPanda** [mcmonkey4eva/Sentinel#137]
**Hi there, my sentinels are not taking damage, I have checked to make sure they have vulnerable on &
invisibly off,
I get this error when I get one.**

`20.02 00:21:59 [Server] WARN java.lang.NoSuchFieldException: Could not resolve field for [ResolverQuery{name='entitiesById', types=[]}] in class class net.minecraft.server.v1_11_R1.WorldServer
20.02 00:21:59 [Server] WARN at org.inventivetalent.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:186)
20.02 00:21:59 [Server] WARN at org.inventivetalent.reflection.resolver.FieldResolver.notFoundException(FieldResolver.java:39)
20.02 00:21:59 [Server] WARN at org.inventivetalent.reflection.resolver.ResolverAbstract.resolve(ResolverAbstract.java:88)
20.02 00:21:59 [Server] WARN at org.inventivetalent.reflection.resolver.FieldResolver.resolve(FieldResolver.java:85)
20.02 00:21:59 [Server] WARN at org.inventivetalent.mapmanager.MapManagerPlugin.getItemFrameById(MapManagerPlugin.java:155)
20.02 00:21:59 [Server] WARN at org.inventivetalent.mapmanager.event.MapInteractEvent.getItemFrame(MapInteractEvent.java:78)
20.02 00:21:59 [Server] WARN at org.inventivetalent.mapmanager.PacketListener$1.onReceive(PacketListener.java:77)
20.02 00:21:59 [Server] WARN at org.inventivetalent.packetlistener.handler.PacketHandler.notifyHandlers(PacketHandler.java:131)
20.02 00:21:59 [Server] WARN at org.inventivetalent.packetlistener.PacketListenerAPI.onPacketReceive(PacketListenerAPI.java:133)
20.02 00:21:59 [Server] WARN at org.inventivetalent.packetlistener.channel.ChannelAbstract.onPacketReceive(ChannelAbstract.java:117)
20.02 00:21:59 [Server] WARN at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:179)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
20.02 00:21:59 [Server] WARN at org.inventivetalent.packetlistener.channel.INCChannel$ChannelHandler.channelRead(INCChannel.java:182)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
20.02 00:21:59 [Server] WARN at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
20.02 00:21:59 [Server] WARN at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
20.02 00:21:59 [Server] WARN at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
20.02 00:21:59 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
20.02 00:21:59 [Server] WARN at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
20.02 00:21:59 [Server] WARN at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
20.02 00:21:59 [Server] WARN at java.lang.Thread.run(Thread.java:745)`

**Comment by mcmonkey4eva** [comment]
Non-Sentinel error; `MapManagerPlugin` is the source of... whatever that is.

**Comment by TheSodaPopPanda** [comment]
Hmm okay that is a dependence plugin, eh,
Okay thanks a lot

**Comment by TheSodaPopPanda** [comment]
If I can find a fix that is not deleting it is will post here :)
