### ISSUE TITLE
Loose target and dont chase?

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#139]
When a NPC dont see a target in his chase range, he dont chase him, that´s good. But when he saw a target one time, he doesnt loose the target after not seeing him. That is in most situations good. But we have some NPCs with bow who don´t should chase someone, which he cant see anymore. Is there an option? Before the update I could change the chaserange to a small and the attack range to a high value. So he shot to him, but didnt chase him. When I try this now, he doesn´t shoot, when the chaserange is small. It´s so difficult to explain :D What I actually want to ask is, if there is an option, that the Sentinel loose the target and don`t chase him, when he cant see him.

**Comment by mcmonkey4eva** [comment]
Just disable chasing for that NPC?

**Comment by Firemonkey08** [comment]
They are walking a path. When I disable chasing, they continue the walk while shooting. We want them staying or trying to come to the target few blocks. while shooting. But when they dont see the target, they shouldnt chase anymore.On an old sentinel version I put chaserange = 5 and attackrange = 20. So they shot 20 meters long, walked some meters on their wall or tower to get a better position, but when they couldnt see me anymore, they walked their path. I know its a special request, so if there is no solution, we will try to find a good alternative.

**Comment by mcmonkey4eva** [comment]
There's an option somewhere to set how long an NPC will continue focusing on a target when it's out of view...

**Comment by Firemonkey08** [comment]
Sounds good. Let me know when u found the option.

PS: Now our server contains several hundred Sentinel NPCs.  A big thank you from all users who use the server goes to you.

**Comment by mcmonkey4eva** [comment]
It's `/sentinel targettime TIME`... when I said "there's an option..." I was kinda hoping you would go look at the readme. Where it's conveniently listed .-.

**Comment by Firemonkey08** [comment]
Oh sorry. I did read it so often and I never saw it. Thanks.
