### ISSUE TITLE
targettime dont change anything

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#140]
It´s me again. The option targettime is exactly that, I was looking for. But to set a value don´t change anything. The NPC is chasing the target an endless time. There is no differenece between he can see the target and he can´t see him.

**Comment by mcmonkey4eva** [comment]
What?

**Comment by Firemonkey08** [comment]
I’m sorry, I don’t speak English very well. I changed the targettime of an NPC to few seconds. Then he found a target and chased him. The target was then behind a wall, so the NPC couldn´t see him anymore. But he tried to go to the target to hunt him more then a few seconds. He tried it an endless time, so he never went back home. I thought the option targettime sets a time limit, after that the NPC goes back and dont chase the target.

**Comment by mcmonkey4eva** [comment]
That is what it does. You can set it to EG `1` for rapid wear-off.

**Comment by Firemonkey08** [comment]
Tried it with "1" also, but he never goes back, he is chasing the target an endless time. I set a pathpoint, and a high pathfindingrange. Do I do something wrong? Would it be an advantage, if I send a video to you?
Sorry, for annoying you. I don´t find my mistake.

**Comment by mcmonkey4eva** [comment]
Uh... sure, send a video, if nothing else it'll ensure we're on the same page here.

**Comment by Firemonkey08** [comment]
So, I recorded the situation:

[https://streamable.com/u4n4p](https://streamable.com/u4n4p)

I thought, the sentinel should not chase me, when I´m going out of his line of sight.

**Comment by mcmonkey4eva** [comment]
It completes the previous motion before returning to base, to avoid players being able to just hide around a corner and nothing more like what you did in the video.

**Comment by Firemonkey08** [comment]
ok, what does the targettime do then? Because he will chase me an endless time, while he never can see me.

**Comment by mcmonkey4eva** [comment]
It shouldn't chase you "an endless time"... if you go farther away then just hiding around a corner. Exit the range or avoid it more complexly (EG turn /multiple/ corners)
