### ISSUE TITLE
No explanation for /sentinel squad command? 

### ISSUE THREAD

**Issue by Steffbeard** [mcmonkey4eva/Sentinel#142]
What does it do?
Does it allow for formations to be made? 
Can you order entire squads to do something?

If not then you should add those features. :)

It could be like /sentinel select (Squad) and then it would select those NPCs

**Comment by mcmonkey4eva** [comment]
Squad just means they will protect other NPCs in their squad if any one of them is attacked. They share targets.

Multi-select would be a feature of base Citizens (one that probably wouldn't be added, being such a big change for a small result).
