### ISSUE TITLE
Finding only Targets in line of sight

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#145]
There is no option, that an npc find only targets he can see, so they have to be in his line of sight, is there? 
Then a target could stalking from behind.

**Comment by mcmonkey4eva** [comment]
That is the on and enforced by default.

**Comment by Firemonkey08** [comment]
Now they dont see the target behind a wall. That´s good. But I mean if they could not see a target behind them, without obstacle in the way. Then the target could stalking from behind. The Sentinel wouldn´t notice him until he is turning around.

**Comment by mcmonkey4eva** [comment]
Ah, that's different. I could add that, sure.

**Comment by mcmonkey4eva** [comment]
Sorry for slow dev!
I added it!
`/sentinel realistic`
