### ISSUE TITLE
Npcs respawn, where they died

### ISSUE THREAD

**Issue by gdavid04** [mcmonkey4eva/Sentinel#147]
I can't make, that they respawn at their spawn point.

**Comment by mcmonkey4eva** [comment]
... Did you set a spawn point via command?

**Comment by Firemonkey08** [comment]
I noticed that the command /npc spawn and a server restart let them spawn at the position, where they died. Only the respawn after the respawntime let them spawn at their spawn point. I would prefer if they would spawn everytime at their spawn point.

**Comment by mcmonkey4eva** [comment]
That's out of Sentinel's control if you do the `/npc spawn` command.

**Comment by gdavid04** [comment]
They respawn where they died after manually killing them.
This also occurs when i type /sentinel kill.
Yes, i have set a spawn point.

**Comment by Oruss7** [comment]
i had the same problem, npcs respawn at death location or when server startup, on last location...

**Comment by mcmonkey4eva** [comment]
Likely conflicting plugins (EG Denizen or similar with its own respawn functionality)

**Comment by Sprungente** [comment]
That very bad. I have this problem too and my sentinel's are to stupid to walk back i don't know why.

I use 
Combatnocheatplus
Worldguard 

maybe one of them can make conflict but i think not

**Comment by mcmonkey4eva** [comment]
Still an issue?
