### ISSUE TITLE
Fighting and moving in water

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#148]
If a sentinel falls into water, he comes out when he wants to go home. But he is still standing while seeing his target. He doesn´t move and fight badly in water. avoidwater is false. Is it difficult to fix?

**Comment by mcmonkey4eva** [comment]
Eh... enable avoid water? :D 
The limitations of water movement for non-players are within minecraft and Citizens, and have nothing to do with the Sentinel combat system...

**Comment by Firemonkey08** [comment]
Enable avoid water isn´t better because in a combat they will pushed in the water. When they want to go home, they find the path and they get out of the water. Only in a combat they don´t move. Because of this I thought it´s a sentinel problem...
