### ISSUE TITLE
Own plugin: get spawnpoint

### ISSUE THREAD

**Issue by Firemonkey08** [mcmonkey4eva/Sentinel#149]
I want to write a plugin, that teleport the Sentinel to their spawnpoints. I load the citizens API, and I put all NPCs, which I want to have, in an array. My question is, if I can get easily the spawnpoint of an Sentinel. Or do I have to load the saves.yml and get the spawnpoint manualy.

**Comment by mcmonkey4eva** [comment]
`npc.getTrait(SentinelTrait.class).spawnPoint`

**Comment by Firemonkey08** [comment]
thanks. How do I load the sentinel api?

**Comment by mcmonkey4eva** [comment]
... by learning how Java functions? That's a basic thing to know how to do...

**Comment by Firemonkey08** [comment]
ok. I will search it. I learned java by myself with learning by doing. I wrote complex plugins with thousands of lines but I never needed to load others APIs :D 
Thanks :)
