### ISSUE TITLE
Remove Glowing effect?

### ISSUE THREAD

**Issue by Loapu** [mcmonkey4eva/Sentinel#151]
I recently createt a NPC with a spectral arrow as weapon. My friend and I got "glowiefied" but we don't know a way to disable our glow because it isn't a normal effect :/ Any suggestions?

**Comment by mcmonkey4eva** [comment]
TBH adding that feature wasn't my best plan.

I'm sure there's a way to remove it somehow using game (either via command or milk or something) (I think dying in game should also remove it)

But the way I can guarantee will work easily and safely is via Denizen https://wiki.citizensnpcs.co/Denizen -> just load up the latest dev build and go in-game, type `/ex adjust <player> glowing:false` and it'll get rid of glowing effect on the player that did it. Swap `<player>` for EG `p@MyFriendsNameHere` to have it clean up someone else.

**Comment by Loapu** [comment]
Thank you for your help ^^ I tried command blocks, milk, /effect command, dieing, server reboot etc. nothing of this things worked for me. I'll leave a comment weather Denizen worked for me or not

**Comment by Loapu** [comment]
It worked, thank you ^^

**Comment by BDenBleyker** [comment]
I am having this problem, and the `/ex adjust p@yodarocks1 glowing:false` (my IGN is yodarocks1) didn't work.

**Comment by mcmonkey4eva** [comment]
It should work... was there any error message?

**Comment by BDenBleyker** [comment]
"Too many parameters! Unused parameters: p@yodarocks1 glowing:false    Usage: //ex [radius]"
I now realize that there were two /'s. Is there an alias for /ex?

**Comment by mcmonkey4eva** [comment]
You need to install Denizen dev for that command, as the earlier post said.

**Comment by BDenBleyker** [comment]
Okay. I will try that.

**Comment by ChimpGamer** [comment]
The command didn't worked for me. I installed Denizen and run the command and this is the output:
`11.09 20:57:23 [Server] INFO ChimpGamer issued server command: /ex adjust Jeroen123 glowing:false
11.09 20:57:23 [Server] INFO Starting InstantQueue 'EXCOMMAND_StruckTransportMore'... 
11.09 20:57:23 [Server] INFO Queue 'EXCOMMAND_StruckTransportMore' Executing: ADJUST 
11.09 20:57:23 [Server] INFO "Jeroen123" "glowing:false" 
11.09 20:57:23 [Server] INFO +- Executing dCommand: ADJUST/p@ChimpGamer ---------+ 
11.09 20:57:23 [Server] INFO +> Executing 'ADJUST': object='Jeroen123'  mechanism='glowing' 
11.09 20:57:23 [Server] INFO mechanism_value='false' 
11.09 20:57:23 [Server] INFO ERROR! Unfetchable object found 'Jeroen123'! 
11.09 20:57:23 [Server] INFO Completing queue 'EXCOMMAND_StruckTransportMore' in 0ms. `

![2017-09-11_20 56 06](https://user-images.githubusercontent.com/19960733/30291814-4d1a32de-9734-11e7-9a85-6944c996a0d6.png)

**Comment by MusicScore** [comment]
You need to replace "Jeroen123" with "p@<username>", so in your case "p@Jeroen123". If you're the one running the `/ex` command, you can replace "p@<username" with just "player" (for example, `/ex adjust player glowing:false`)

**Comment by ChimpGamer** [comment]
I tried that before I used /ex adjust Jeroen123 glowing:false but that didn't work either.

**Comment by MusicScore** [comment]
I'll assume you've tried dying, `/effect Jeroen123 glowing 0`, etc., and have installed Denizen?

**Comment by ChimpGamer** [comment]
Yep

**Comment by MusicScore** [comment]
It can plausibly be because you're in a scoreboard team, if nothing's worked so far. You can try `/scoreboard teams leave Jeroen123` and see if that works. If not, then you're have some witchcraft going on or a glowing NPC that has your exact username (with no color codes in it).

**Comment by ChimpGamer** [comment]
There are no glowing NPC's with the same name as him. Also I tried the command but that didn't worked either :/

**Comment by MusicScore** [comment]
Let me ask, how did you get the glowing effect on you? And what version of Denizen do you have?

**Comment by ChimpGamer** [comment]
It was caused by an Sentinal NPC's that shot and spectral arrow on that player. The issues has been caused a few weeks ago. And I got the latest dev build of Denizen.

**Comment by MusicScore** [comment]
You are absolutely sure, then, that you've run these commands:
```
/ex adjust player glowing:false
/ex adjust p@Jeroen123 glowing:false
/scoreboard teams leave Jeroen123
/effect Jeroen123 clear
```
and is still glowing?

**Comment by ChimpGamer** [comment]
Exactly yes!

**Comment by mcmonkey4eva** [comment]
In addition to the command MusicScore gave above (Should work if input as written):
Have you removed the NPC that gave the glow?
What's present console output for the `/ex` command listed by MusicScore above?

**Comment by ChimpGamer** [comment]
The NPC that gave the glowing effect to the player doesn't exist anymore and /ex returns (Tried both)
`12.09 18:33:05 [Server] INFO ChimpGamer issued server command: /ex adjust @pJeroen123 glowing:false
12.09 18:33:05 [Server] INFO Starting InstantQueue 'EXCOMMAND_PeriodicallyLeastThumb'... 
12.09 18:33:05 [Server] INFO Queue 'EXCOMMAND_PeriodicallyLeastThumb' Executing: ADJUST 
12.09 18:33:05 [Server] INFO "@pJeroen123" "glowing:false" 
12.09 18:33:05 [Server] INFO +- Executing dCommand: ADJUST/p@ChimpGamer ---------+ 
12.09 18:33:05 [Server] INFO +> Executing 'ADJUST': object='@pJeroen123'  
12.09 18:33:05 [Server] INFO mechanism='glowing'  mechanism_value='false' 
12.09 18:33:05 [Server] INFO ERROR! Unfetchable object found '@pJeroen123'! 
12.09 18:33:05 [Server] INFO Completing queue 'EXCOMMAND_PeriodicallyLeastThumb' in 0ms. 
12.09 18:33:09 [Server] INFO ChimpGamer issued server command: /ex adjust Jeroen123 glowing:false
12.09 18:33:09 [Server] INFO Starting InstantQueue 'EXCOMMAND_TilLastingArray'... 
12.09 18:33:09 [Server] INFO Queue 'EXCOMMAND_TilLastingArray' Executing: ADJUST 
12.09 18:33:09 [Server] INFO "Jeroen123" "glowing:false" 
12.09 18:33:09 [Server] INFO +- Executing dCommand: ADJUST/p@ChimpGamer ---------+ 
12.09 18:33:09 [Server] INFO +> Executing 'ADJUST': object='Jeroen123'  mechanism='glowing' 
12.09 18:33:09 [Server] INFO mechanism_value='false' 
12.09 18:33:09 [Server] INFO ERROR! Unfetchable object found 'Jeroen123'! 
12.09 18:33:09 [Server] INFO Completing queue 'EXCOMMAND_TilLastingArray' in 0ms. `

**Comment by mcmonkey4eva** [comment]
it's ... `p@` not `@p`.
Also, ensure the player you're doing it for is online of course.
