### ISSUE TITLE
Making sentinel go back to his previous position

### ISSUE THREAD

**Issue by Bartol0ll0** [mcmonkey4eva/Sentinel#152]
Is it possible for sentinel to go back to his "spawn" position after he defeated his target?

**Comment by Firemonkey08** [comment]
If you set one or more pathpoints, they will go back to one of them. You can set it with the command "/npc path" and then left mouseclick to add a point and right click to remove a point. If you set more points, he will patrol between them.
Important is, that the pathfindingrange is high enough to find a pathpoint. Set it with "/npc pathrange <distance in blocks>".

**Comment by Bartol0ll0** [comment]
It kind of works,but sentinels in mid fight go back to waypoint and then back to fight and run in circles.Is there a workaround for this?

**Comment by Firemonkey08** [comment]
Check your chaserange `/sentinel chaserange.` If the distance to the target is higher then this chaserange, he run in circles. Chaserange set the distance he will chase a target. `/sentinel range` set the distance, he will notice a target (or shoot him with arrow).

**Comment by Bartol0ll0** [comment]
I get the idea of `/sentinel chaserange`,I have set it up, but it looks like the guard doesn't know if it should follow the target or go to set waypoint so he gets stuck running between his path and target

**Comment by Firemonkey08** [comment]
I had this problem some weeks ago. But now the problem is solved to me. Do you use the current build 108?
