### ISSUE TITLE
Animal NPCs becoming invisible when using Sentinel

### ISSUE THREAD

**Issue by izShelby** [mcmonkey4eva/Sentinel#154]
I really wonder how this could happen, but all non-human NPCs on my server become invisible once I install Sentinel. I can hear the type of mob I used (for example moo-ing in cows) but they don't appear. No errors or warnings in the logs whatsoever. 
I tried respawning them, creating new ones, nothing works.

Here's my full plugin list, in case it's a known conflict.
Plugins (36): dynmap, WorldEdit, TimTheEnchanter, Sting, Spectate, Essentials, MinePacks, LogBlock, ClearLag, PluginManagerReloaded, Bloodshed, Modifyworld, WorldBorder, LWC, Multiverse-Core, WorldGuard, NoCheatPlus, Citizens, EssentialsXMPP, Admin-Chat, ChestRestock, EssentialsGeoIP, PermissionsEx, AddLight, TrollBoss, CS-CoreLib, ChatEx, EssentialsSpawn, Denizen, pvparena, HolographicDisplays, Slimefun, SlimefunLuckyBlocks, ExoticGarden, CombatIndicator, TouchscreenHolograms

I am using Citizens 2.0.21.

**Comment by mcmonkey4eva** [comment]
That shouldn't be possible to induce through Sentinel. Sentinel does not affect any of that relevant code.

It might just have forced a re-ordering of plugins, causing some bad unrelated plugin to take priority and win the fight for how entities work.

**Comment by izShelby** [comment]
I will conduct some tests tomorrow and let you know what I find out.

**Comment by izShelby** [comment]
Issue has randomly resolved itself. Go figure.
