### ISSUE TITLE
[Enhancement] Open shulker where a target is focused

### ISSUE THREAD

**Issue by Eredrim** [mcmonkey4eva/Sentinel#155]
Hello,
I just would suggest this enhancement : open a shulker when a target is in the target range.

**Comment by mcmonkey4eva** [comment]
Are you using NPC shulkers with Sentinel?

**Comment by Eredrim** [comment]
Yes, and it works.

**Comment by mcmonkey4eva** [comment]
Spigot seems to lack a method for this as far as I can see.

Perhaps @fullwall can help here by providing a Citizens trait or NMS wrapper call to trick it open/close?

**Comment by fullwall** [comment]
Added

**Comment by mcmonkey4eva** [comment]
:D!
Sentinel DEV-145+ contains autoshulker.
http://ci.citizensnpcs.co/job/Sentinel/

Important note: do not use the shulker command or trait now available in Citizens, as it will
A: Override the Sentinel input
B: Spam sound effects for some reason
