### ISSUE TITLE
Must have an NPC selected!

### ISSUE THREAD

**Issue by Oruss7** [mcmonkey4eva/Sentinel#156]
I have some troubles to use sentinel. When i try, it say `[Sentinel] Must have an NPC selected!`...
So, i try `/npc sel` and test with some npc commands. Citizens commands works fine but have the message when trying a sentinel command.

sentinel : 1.0 (build 101)
citizens : 2.0.21 (build 1464)

I have denizen too

**Comment by mcmonkey4eva** [comment]
You must have a SENTINEL NPC selected in specific. Enable `/trait sentinel` on the NPC.

**Comment by Oruss7** [comment]
Ah. Can you set `Must be an sentinel` instead please ? I'm confusing...

**Comment by mcmonkey4eva** [comment]
It actually says:
`Must have a Sentinel NPC selected! Use /trait sentinel to ensure an NPC becomes a Sentinel.`

On the current version.

You're running an older version.
