### ISSUE TITLE
Denizen Commands

### ISSUE THREAD

**Issue by Arctomium** [mcmonkey4eva/Sentinel#157]
You supposedly say that Denizen is compatible with many plugins except for the fact that there is no proof they are because none of the Wikis have commands, one set of commands I've been trying to find is ones that work with Sentinel like the Wiki claims but there is nothing anywhere.

**Comment by mcmonkey4eva** [comment]
Most linkings for Denizen are provided by Depenizen, https://github.com/DenizenScript/Depenizen
and all is documented for that on the main Denizen documentation site: https://one.denizenscript.com/denizen/logs/

Sentinel commands have no reason to be duplicated internally to Denizen, as the `- execute` Denizen command suffices.
EG, `- execute as_server "npc select <npc.id>" - execute as_server "sentinel addtarget COWS"`
There exists a few non-command links to Sentinel available via Depenizen. (All I can remember offhand is an attack event) - more in that category can be added to Depenizen if/when it's requested.
