### ISSUE TITLE
event:pvp (and others) not working

### ISSUE THREAD

**Issue by Keitokun** [mcmonkey4eva/Sentinel#158]
NPC does attack (PLAYERS and MONSTERS is working). If i try event:pvp, event:pvnpc or the other ones, the npc does nothing. :(
More Information: I did removed all Ignors. Server version: Spigot 1.11.2

**Comment by mcmonkey4eva** [comment]
Is PvP actually validly happening without any intermediary plugins in the direct line-of-sight for the NPC Sentinel?
