### ISSUE TITLE
No NPCs will attack or follow, they will disappear if mobtype is not player?

### ISSUE THREAD

**Issue by Moderocky** [mcmonkey4eva/Sentinel#159]
Hi I am using the LATEST version of sentinel and Citizens2.

In this version while Sentinel is installed, only NPCs of type PLAYER will be visible. Others will just disappear.

If I use an earlier Sentinel version then other mobs will appear.

In both versions, NPCs will not attack/follow people.

**Comment by mcmonkey4eva** [comment]
Sentinel shouldn't make things disappear, excluding by plugin rearrangement coincidence. Try it without unrelated plugins.

**Comment by Moderocky** [comment]
It is only when I install sentinel with the latest citizens that they disappear.




---- On Mon, 03 Apr 2017 09:32:37 +0000 mcmonkey &lt;notifications@github.com&gt; wrote ----




Sentinel shouldn't make things disappear, excluding by plugin rearrangement coincidence. Try it without unrelated plugins.

**Comment by mcmonkey4eva** [comment]
Sorry for late response: you never tested my previous request.
