### ISSUE TITLE
Unable to add targets to several NPCs

### ISSUE THREAD

**Issue by Axlnh** [mcmonkey4eva/Sentinel#160]
Hello, first of all, thanks for this awesome plugin.
I downloaded both Citizens 2 and Sentinel (last versions) and everything is working fine, but,
When creating 2 NPCs, giving them a sword and then typing "/sentinel addtarget zombie" it says "Must have an NPC selected". I tried to do "/npc sel" and every of these commands but it's still telling me the same error.

Can anyone help me please ? Sorry if it's logical but I really can't get it, even with tutorials,
Thanks in advance to everyone that will try to help me :)

**Comment by mcmonkey4eva** [comment]
Add `/trait sentinel`

The error message is clearer in more recent builds

**Comment by Axlnh** [comment]
I already did it. Weirdly replacing "/trait sentinel" by "/trait Sentinel" worked.
Thanks for your answer.
