### ISSUE TITLE
Disable kills counting as "player kills"

### ISSUE THREAD

**Issue by i9hdkill** [mcmonkey4eva/Sentinel#161]
Right now, killing npcs are counting against player kills.
Thats kinda bad if you have plugins that are counting player kills to calculate a kdr or similiar.

A config option to disable that would be pretty neat.

**Comment by mcmonkey4eva** [comment]
tbh I'm not sure how I would change that; Player NPCs are players as far as minecraft and incompatibly built plugins are concerned.

**Comment by mcmonkey4eva** [comment]
It'd probably be best to ask the creators of the KDR plugin to add a simple easy check to ensure the `NPC` metadata is not present on a player entity.

**Comment by i9hdkill** [comment]
Yep, after looking into it, this is the right way to do it. Sry for bothering you.
