### ISSUE TITLE
Sentinel trait not being added?

### ISSUE THREAD

**Issue by Justind5700** [mcmonkey4eva/Sentinel#164]
I can't seem to get sentinels working, I have the correct version matching I believe. Thank you for taking a look at this, I would love getting this resolved.

27.05 12:28:50 [Server] INFO TheHolySkittles issued server command: /trait sentinel
27.05 12:28:50 [Server] WARN java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
27.05 12:28:50 [Server] WARN at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:437)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:100)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:89)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:157)
27.05 12:28:50 [Server] WARN at sun.reflect.GeneratedMethodAccessor267.invoke(Unknown Source)
27.05 12:28:50 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
27.05 12:28:50 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
27.05 12:28:50 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:237)
27.05 12:28:50 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
27.05 12:28:50 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
27.05 12:28:50 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
27.05 12:28:50 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.05 12:28:50 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
27.05 12:28:50 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
27.05 12:28:50 [Server] WARN at java.lang.Thread.run(Thread.java:745)

**Comment by mcmonkey4eva** [comment]
You need specifically the 1.10 version from https://wiki.citizensnpcs.co/Versions#Sentinel_Versions

**Comment by Justind5700** [comment]
It worked, thanks!
