### ISSUE TITLE
I have problems on Sentinel

### ISSUE THREAD

**Issue by tonicsense** [mcmonkey4eva/Sentinel#165]
My Server always crashes when the npc moves towards me. I tried 1.3.1, 1.3 and 1.0 . 
My Server version 1.8.8
Is  there any version you can recommend me for 1.8.8?
-tonicsense
btw if it helpes here the crash code
`
22.06 13:46:45 [Multicraft] Skipped 81 lines due to rate limit (30/s) 22.06 13:46:44 [Server] INFO at net.citizensnpcs.npc.entity.EntityHumanNPC.t_(EntityHumanNPC.java:289) ~[?:?] 22.06 13:46:44 [Server] INFO at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:266) ~[?:?] 22.06 13:46:44 [Server] INFO at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:415) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1789) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1655) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.updateTargets(SentinelTrait.java:1604) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.getEntityForID(SentinelTrait.java:1599) ~[?:?] 22.06 13:46:44 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Server.getEntity(Ljava/util/UUID;)Lorg/bukkit/entity/Entity; 22.06 13:46:44 [Server] ERROR Cause of unexpected exception was 22.06 13:46:44 [Server] INFO ... 4 more 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.World.g(World.java:1582) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.citizensnpcs.npc.entity.EntityHumanNPC.t_(EntityHumanNPC.java:289) ~[?:?] 22.06 13:46:44 [Server] INFO at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:266) ~[?:?] 22.06 13:46:44 [Server] INFO at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:415) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1789) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1655) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.updateTargets(SentinelTrait.java:1604) ~[?:?] 22.06 13:46:44 [Server] INFO at org.mcmonkey.sentinel.SentinelTrait.getEntityForID(SentinelTrait.java:1599) ~[?:?] 22.06 13:46:44 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getEntity(Ljava/util/UUID;)Lorg/bukkit/entity/Entity; 22.06 13:46:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:797) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52] 22.06 13:46:44 [Server] INFO net.minecraft.server.v1_8_R3.ReportedException: Ticking entity 22.06 13:46:44 [Server] ERROR Encountered an unexpected exception 22.06 13:46:44 [Server] INFO tonicsense issued server command: /we cui 22.06 13:46:43 [Multicraft] tonicsense ran command Nachricht des Tages
`

**Comment by mcmonkey4eva** [comment]
Looks like there's an important method missing in your 1.8.8 install? 0.o

Might have not use whatever command triggered that,  as I'm not particularly able to support such a broken outdated version.

Or, y'know, just update your server lol
