### ISSUE TITLE
Using bow on a 1.8.8 server crashes the server

### ISSUE THREAD

**Issue by kh498** [mcmonkey4eva/Sentinel#166]
When giving a sentinel a bow on a 1.8 r3 server the server will throw an exception and shut down.
[server dump](https://pastebin.com/ZxdU8T8s)

I think the error is [here](https://github.com/mcmonkey4eva/Sentinel/blob/master/src/main/java/org/mcmonkey/sentinel/SentinelTrait.java#L794)

**Comment by mcmonkey4eva** [comment]
That's a fixed bug, you can see the fix in the code link you sent lol

Download latest dev build: http://ci.citizensnpcs.co/job/Sentinel/

**Comment by kh498** [comment]
oh  yeah i thought i was weird that it checked for the version :P
