### ISSUE TITLE
Npc don't drop

### ISSUE THREAD

**Issue by Sprungente** [mcmonkey4eva/Sentinel#167]
At first: Enemydrops are active

Npc is standing in a Worldguardregion with only greeting farewell and pvp allow flag

When he is killing from a player, they don't drop they inventory. Inventory was set with /sentinel drops.

I use Sentinel Build 125
Citizens Build 1481
This server is running CraftBukkit version git-Spigot-23b6354-0481ae9 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

plugins they can manipulate it:
CompatNoCheatPlus last build from jenkins
Worldguard Build 1708 

Thanks for helping, fixing and working

**Comment by mcmonkey4eva** [comment]
It may be dropped by a plugin or gamerule.

It's easy enough to workaround - just set the `workaround drops` config option to true!
https://github.com/mcmonkey4eva/Sentinel/blob/master/src/main/resources/config.yml#L46
