### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by TeeKay1** [mcmonkey4eva/Sentinel#169]
This just started happening today. Not sure what's causing it.

Sentinel stat issue: Server returned HTTP response code: 500 for URL: http://neo.mcmonkey.org/plugins/public_stats?plugin=Sentinel&version=1.3.1+%28build+126%29

**Comment by mcmonkey4eva** [comment]
Sorry about that, the public stats server crashed apparently... it's back online, so that error should be gone.
