### ISSUE TITLE
On the latest versions, NPC doesn't attack their targets

### ISSUE THREAD

**Issue by Eredrim** [mcmonkey4eva/Sentinel#171]
Hi,
I have problems on the latest versions, NPC don't attack their target because new target name is without "s" at the end and the former no. So, I need to add new target to the NPCs but the older version stays when I type /sentinel targets.
In this ticket (opened in the bad repository) https://github.com/DenizenScript/Denizen-For-Bukkit/issues/1606 , you told me you will make something for this, but this is limited to "direct" attackers sentinel and it does not affect remote attackers (like archers). It doesn't remove the old tag either. 

Regards,

**Comment by mcmonkey4eva** [comment]
Are you running a _developmental build_? That was introduced in one dev build and fixed in a more recent one... http://ci.citizensnpcs.co/job/Sentinel/

**Comment by Eredrim** [comment]
I tried with a dev build and with the latest release.

**Comment by mcmonkey4eva** [comment]
The latest dev build should automatically restore targets that were lost by the name exactness change...

**Comment by Eredrim** [comment]
Ok. I will try that this evening (GMT+1). I will keep you informed.

**Comment by Eredrim** [comment]
Hello,
sorry, I'm in late. I tested your latest dev build and the problem is the same.

**Comment by mcmonkey4eva** [comment]
Sorry for non response, is this still an issue?
