### ISSUE TITLE
Sentinel win achievements

### ISSUE THREAD

**Issue by Eredrim** [mcmonkey4eva/Sentinel#173]
Hello,

In 1.12, with the latest version of sentinel and spigot, sentinels can win achievements like "monster hunter". Can you remove it ?

**Comment by mcmonkey4eva** [comment]
as far as minecraft cares, if you kill a monster you kill a monster.

What's wrong with this behavior?

**Comment by Eredrim** [comment]
Citizens are not real players, it is really strange to see achievements appear in chat for npc.
Moreover, I don't think it existed in previous versions.

**Comment by mcmonkey4eva** [comment]
Oh wait, I misunderstood what you meant. That's indeed out-of-band to happen... I think it'd be key for Citizens to prevent that normally? As Sentinel isn't the only way an NPC might end up getting an achievement...

**Comment by Eredrim** [comment]
I'm really sorry but I don't understand you this time. My English default me. Can you ask your question again in a simpler way ?

**Comment by mcmonkey4eva** [comment]
I believe this is an issue for the Citizens plugin to correct, not Sentinel.

**Comment by Eredrim** [comment]
Oh ! ok. Do you want I create a Citizens ticket or have you a way to forward them ?

**Comment by mcmonkey4eva** [comment]
Yeah, you should create the issue post.
