### ISSUE TITLE
Suggestion: Automatic Interval Respawn (Regardless of Death)

### ISSUE THREAD

**Issue by TheNoodleMan** [mcmonkey4eva/Sentinel#174]
I sincerely apologize if this is already a feature; I can't seem to find it if it is.

This suggestion is pretty simple: If a Sentinel hasn't been interacted with (Taken Damage/Dealt Damage) in a specified amount of time, it respawns back at their Set Spawn Point.

This'd be helpful for Sentinels set around elevated platforms or platforms above water, so that if they're knocked-off they'll be placed back in their designated spot.

Thanks in advance for any feedback!

**Comment by mcmonkey4eva** [comment]
You might be interested in `/npc path` to set a point: They'll automatically go to that point whenever they're not chasing a target.
