### ISSUE TITLE
1.7.10 Version?

### ISSUE THREAD

**Issue by Jaysalina** [mcmonkey4eva/Sentinel#175]
Is there by chance a 1.7.10 version, I enjoy using Citizens2 however the only problem for me is that I am aiming for the whole works of RPG. I know that Sentinel would be a great addition to the server. Just curious if you have a 1.7.10 version since Sentry no longer works.

**Comment by mcmonkey4eva** [comment]
Sentry should work fine on ancient versions like that. Sentinel has no reason to support 1.7.10 considering its extreme outdatedness.


I would strongly recommend you just find a way to use a more up-to-date version of MC for your needs.
