### ISSUE TITLE
DistanceSquared trying to measure between worlds with players teleport

### ISSUE THREAD

**Issue by Nutty101** [mcmonkey4eva/Sentinel#176]
This was from someone else, but figured I would add it here.

When a user is the active target for an NPC running Sentinel and they teleport to another world, you get a ton of errors trying to measure the distance between the NPC and player.

> [23:02:03] [Server thread/INFO]: [Citizens] Exception while updating 112: Cannot measure distance between world and spawn.
> [23:02:03] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot measure distance between world and spawn
> [23:02:03] [Server thread/WARN]:    at org.bukkit.Location.distanceSquared(Location.java:455)
> [23:02:03] [Server thread/WARN]:    at ***org.mcmonkey.sentinel.SentinelTrait.updateTargets(SentinelTrait.java:1625)***
> [23:02:03] [Server thread/WARN]:    at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1663)
> [23:02:03] [Server thread/WARN]:    at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1797)
> [23:02:03] [Server thread/WARN]:    at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:430)
> [23:02:03] [Server thread/WARN]:    at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:268)
> [23:02:03] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:151)
> [23:02:03] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1638)
> [23:02:03] [Server thread/WARN]:    at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1005)
> [23:02:03] [Server thread/WARN]:    at net.citizensnpcs.util.NMS.tick(NMS.java:270)
> [23:02:03] [Server thread/WARN]:    at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36)
> [23:02:03] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
> [23:02:03] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
> [23:02:03] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
> [23:02:03] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
> [23:02:03] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
> [23:02:03] [Server thread/WARN]:    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
> [23:02:03] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)

**Comment by mcmonkey4eva** [comment]
Tell the user to update lol. This was fixed a fair while ago.
