### ISSUE TITLE
Searching for updates or gathering stats?

### ISSUE THREAD

**Issue by SlimeDog** [mcmonkey4eva/Sentinel#177]
Spigot 1.12
Citizens 2.0.22-b1485
Sentinel 1.3.1-b119

On server startup:
> [06:29:16 INFO]: Sentinel stat issue: Server returned HTTP response code: 500 for URL: http://neo.mcmonkey.org/plugins/public_stats?plugin=Sentinel&version=1.3.1+%28build+119%29

If this is checking for updates, please provide a configuration option to disable it. I have a home-grown automatic plugin update checker.

If this is gathering statistics, please document what data are being collecting and how they are being used, and provide a configuration option to disable collection. Or turn it off and use bStats. I don't mind stats being collected, but not under the covers.

**Comment by mcmonkey4eva** [comment]
Anyone unwilling to use a primitive stats server that collects nothing more than a total number of online servers and the most popular versions list, should not be running plugins that collect stats in the first place.

It's not "under the covers" so much as "If you're not screwing with developmental details anyway, you don't need to know or care about this feature".
I've seen a few plugins use dual stat servers - one of the PluginMetrics of old and one a dedicated non-disableable second server. The difference in numbers between the two is painful, and shows many people will turn off stat collection (a system which does zero harm to them) and thus mess with accurate usage statistics. A stats server can't be accurate if at least a third of all servers have it turned off...
The paranoia in bukkitland regarding statistics is painful - just add a stats recorder and move on, there's no reason to add 35 warnings, two disabler options, and a public announcement reminder once a week.

Anyway, remote statistics server crashed for a bit today and is now back online - thanks for the report.
