### ISSUE TITLE
Chaseranged with Crackshot Guns not working as it should

### ISSUE THREAD

**Issue by CollectAndroid** [mcmonkey4eva/Sentinel#178]
I'm having issues when i equip a NPC (Type player) with a gun: It just keeps standing at his location and never moves towards the player or tries to chase him if he is around a corner etc... Also if i create a path for a NPC, he walks it and if a target enters his range he stops walking his path and chases the target until the target dies, and then walks back to his path to continue walking it. But not if i equip it with a gun: He just keeps walking his path if a enemie target. He tries turn around and he also shoots, but he is still forced to walk his path and so he will never chase the target or shoot in its direction. Would be very nice if that could be fixed, as i really need that feature!
(I'm sorry for my bad english)

**Comment by mcmonkey4eva** [comment]
Try build 127+ off http://ci.citizensnpcs.co/job/Sentinel/ - I pushed a fix to the new version

**Comment by CollectAndroid** [comment]
Wow! Thank you so much! It's working perfectly now! :D
