### ISSUE TITLE
Kill command

### ISSUE THREAD

**Issue by ThijsSlop** [mcmonkey4eva/Sentinel#18]
Hey, can you add a /sentinel kill command?
(sorry for so many bug reports/feature requests)

**Comment by mcmonkey4eva** [comment]
What would it do?

**Comment by ThijsSlop** [comment]
Kill the NPC and spawn it at the spawnpoint of that NPC. I know there already is a /npc despawn command but if you respawn the NPC, it will not be teleported to the spawn
