### ISSUE TITLE
NPC doesn't forget player after death. Need Help

### ISSUE THREAD

**Issue by lilmistermadness** [mcmonkey4eva/Sentinel#181]
Hi There.
               I was wondering if its possible to set the NPC so that it will only fight whilst being attacked. So it resets its targets after combat is ceased

**Comment by JennaDiamonds** [comment]
GreenFlagCZ, /sentinel forgive works fine. But that's not what lilmostermadness is asking about.

**Comment by mcmonkey4eva** [comment]
You can configure Sentinel to forget targets once they're out-of-sight.
