### ISSUE TITLE
Entity tamed event broken

### ISSUE THREAD

**Issue by HeadlessJoey** [mcmonkey4eva/Sentinel#182]
Seems the 'on entity tamed' event is broken.
I'm using build 196 development version of denizen and spigot 1.12.

I thought it was only me but someone else in Discord also mentioned it and also tested all the different variants of the event (specific entities...) but with no results.

`    on entity tamed:
        - announce "1tamed <pl.name>"
    on player tames wolf:
        - announce "2tamed <pl.name>"
    on player tames entity:
        - announce "3tamed <pl.name>"
    on wolf tamed:
        - announce "4tamed <pl.name>"`

None of them trigger, not even in the debug.

**Comment by mcmonkey4eva** [comment]
Wrong repo? lol this is the Sentinel repo...
