### ISSUE TITLE
Issue with nuNPC_Destinations

### ISSUE THREAD

**Issue by Mineleague** [mcmonkey4eva/Sentinel#184]
I am attempting to use the Sentinel plugin with nuNPC_Destinations, but when I add the waypoint provider "/waypoint provider npcdestinations" it crashes the server. This only happens with the Sentinel plugin enabled. Below is my console log: 
https://pastebin.com/vniygHrA

**Comment by Mineleague** [comment]
Citizens V. 2.0.16, Sentinel V. 1.3.1, nuNPCDestinations V. 2.1.11

**Comment by mcmonkey4eva** [comment]
Sentinel is only compatible with the default waypoint provider at the moment. It hooks directly into the internals of it (as there's no API available) to gather a safe 'home' point to return to after combat.

**Comment by mcmonkey4eva** [comment]
It's how it determines the home location to return to

**Comment by Mineleague** [comment]
Could you possibly add an option to disable that?

**Comment by mcmonkey4eva** [comment]
Actually, it should automatically disable itself if the waypoint provider is wrong.

I forgot I did that.

Make sure you're running latest dev build.
