### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JennaDiamonds** [mcmonkey4eva/Sentinel#187]
Currently I'm using sentinels as enemies on my server. I am also using a plugin called "SkillAPI." Sometimes they play nice together. Other times not so much. Such as damage being dealt by SkillAPI to the citizens. The calculation just seems weird. For example..

I've set up a skill (like in MMORPGs) through SkillAPI. The skill "should" be doing damage on it's own to the sentinel. On normal mobs and players it works fine. But when I attack a sentinel with it the damage applied is based off of the damage of whatever is in the player's main hand. I am posting this in SkillAPI's github as well.
I would think it is SkillAPI's issue, but to my understanding, sentinels should be effected in the same way as a regular player(Which is effects very well in the same state). For that reason I believe it may be an issue with sentinel. If/when you have time could you look into the issue? :)

Also, I understand you may not have time to build a test server. If you would like to access my server to take a look at the issue in its current habitat, I can send you the IP via PM.

Edits:
There are no errors in the error log, hence why I have not included it.

**Comment by JennaDiamonds** [comment]
This is only occuring when holding an item with damage applied by another plugin such as MyItems or DivineItemsRPG. By editing vanilla dmg (the stuff at the bottom of lore "When in main hand: blah blah") I've been more successful. However there are still weird calculations going on. Damage from DivineItemsRPG isn't even recognized by sentinels. So.. I'm lost. I'll just use the workaround for now. Not sure how to better explain this. Wish I could just show someone to be honest. Trying not to be discouraged by the amount of crazy bugs I keep running into. I should learn Java. fml lol

**Comment by mcmonkey4eva** [comment]
Sentinel overrides damage events just enough to ensure regular items account for armor.

Beyond that, it uses vanilla damage logic and reception. If another plugin can't damage a Sentinel NPC, something is wrong with that plugin I would think. They can be damaged normally by a plugin as best I'm aware.
