### ISSUE TITLE
Knockback

### ISSUE THREAD

**Issue by JennaDiamonds** [mcmonkey4eva/Sentinel#188]
Is there a way to change knockback on a sentinel? I've tried a few plugins to change knockback and none of them are working on the sentinels.

I'm trying to make combat with a sentinel harder. Right now it is possible to machinegun click your attack button and keep them at a distance, which isn't very fair to the poor sentinel haha

**Comment by mcmonkey4eva** [comment]
In what way would you want it to be changeable?

Best I can do from the Sentinel side is to either change it for all situations, or per-npc for all situations.

Last I checked in standard Minecraft (at least in 1.9 through present 1.12) spam clicks were an ineffective attack in general.

**Comment by JennaDiamonds** [comment]
**UPDATE** I'm using a plugin called MyItems for items creation.
https://www.spigotmc.org/resources/myitems-premium-1-7-x-1-12-x.29028/

The abilities that this plugin allows me to place on weapons, such as blindness, poison or others.. actually work when the item is placed in the hand of a sentinel. For example, I put blindness on a sword, equipped the sentinel with it, and when he hits me I am blinded.
There is another stat i tried, which didn't work out so well. It is listedby the plugin as "NBT" and is called "Knockback_Resistance". It doesn't seem to work on sentinels. Would it be possible to add support for this? It's a longshot.. but I have to ask :)

**Comment by mcmonkey4eva** [comment]
Uh... that'd really be a question for the item plugin dev, to integrate Citizens NPCs better...
As far as my side, I'm just providing a standard entity (as is backed by Citizens)

As for spam click attack, if it replicates with normal items, you may be using an option like override damage, which isn't the best estimator of correct Minecraft logic, you might want to disable that if it's an option. (Might also apply to the plugin issue if that is set)
