### ISSUE TITLE
Attack Range

### ISSUE THREAD

**Issue by JennaDiamonds** [mcmonkey4eva/Sentinel#190]
After changing /sentinel Attackrange, the sentinel no longer detects targets automatically. It only fights back when damaged.

**Comment by mcmonkey4eva** [comment]
What'd you change it to 0.o

**Comment by mcmonkey4eva** [comment]
That's rather short...

**Comment by JennaDiamonds** [comment]
most plugins measure distance in blocks. so 2 blocks away for a swords is short? I would have to say your answer is short...

**Comment by mcmonkey4eva** [comment]
Can I ask what command you used?
`/sentinel attackrange` isn't a command.

**Comment by mcmonkey4eva** [comment]
Awaiting response:
Type below once you have a response and we'll reopen and continue this issue :)
