### ISSUE TITLE
[Request] Bring back targeting via Perms.

### ISSUE THREAD

**Issue by TagCraftMC** [mcmonkey4eva/Sentinel#191]
Hi mcmonkey4eva,

Would it be possible to add back targeting by permissions? I know there is group:GROUPNAME but I'd rather attach a temp perm to the player then add and remove them from a a group.

Thanks!

**Comment by mcmonkey4eva** [comment]
Can be done, for sure.

**Comment by mcmonkey4eva** [comment]
BTW the reason this wasn't included earlier is, if you're an op you have all permissions...
IE you'd be automatically the target of every NPC with a perm-based target 0.0

**Comment by mcmonkey4eva** [comment]
Try build DEV-134+ off http://ci.citizensnpcs.co/job/Sentinel/
It features `permission:PERM.KEY` targets!

**Comment by TerraPrimal** [comment]
Oh how you spoil us mcmonkey4eva!
Thanks! 

(Runs back to Eclipse to nuke the pex group code)
