### ISSUE TITLE
Pitch Targeting Problem With Crackshot

### ISSUE THREAD

**Issue by TagCraftMC** [mcmonkey4eva/Sentinel#192]
Hi mcmonkey4eva,

It seems Sentinels with a CrackShot weapons don't target correctly when it comes to Pitch.
They seem to shoot only at eye level even if the target is above that. I have included two screenshots.
The firs is using a basic CS weapon (included) and it firing at the 2-3 block of the tower trying to shoot at the pigs. The second one is using a vanilla bow (correctly).
The green lines are arrows.

Thanks!
https://i.gyazo.com/34f1adf6f78059854097ac838412a7ef.png
https://i.gyazo.com/d482967524da45ad3e0878e684768a46.png
https://pastebin.com/YQQktc92

**Comment by mcmonkey4eva** [comment]
There seems to be a Citizens issue where NPCs won't pitch correctly most of the time.
Could you please report that issue to The Citizens2 page? Feel free to link back to this post if it helps.
