### ISSUE TITLE
Bring back mounts

### ISSUE THREAD

**Issue by Galactic-dragon** [mcmonkey4eva/Sentinel#193]
As this is a replacement of sentry can you make these NPC's ride horses?

**Comment by mcmonkey4eva** [comment]
Yes.
`/npc mount`
Spawn a horse and mount the Sentinel NPC onto it with that command.

**Comment by Galactic-dragon** [comment]
THANK YOU I did not think you will respond what with this project being quite old and all.

**Comment by mcmonkey4eva** [comment]
This project is not that old lol. last commit 11 days ago :P
