### ISSUE TITLE
Bring back mounts 

### ISSUE THREAD

**Issue by Galactic-dragon** [mcmonkey4eva/Sentinel#194]
I have already made a issue for this and i was told to do /npc mount. unfourtunetly it makes me mount the npc rather than make the npc mount the horse. 
P.S I know its offtopic but Did you not contribute to the builder project well if you did everytime i do /builder build it gives me a internal error I dont think this is the problem but i am using a version 1.11 builder version (which is the latest) on a 1.12.1 spigot server. if that is the problem can you update it please.

**Comment by mcmonkey4eva** [comment]
I'm not in charge of Builder.
Anyway there's a Citizens command _somewhere_ for mounting an NPC on another, there's a whole system on the internals to keep it across chunk reloads and whatever, it's all part of Citizens and not the job of Sentinel. Also please respond to existing issues, don't just spam new ones :(

**Comment by Galactic-dragon** [comment]
oh ok I thought I could'nt comment on it because you closed it.
