### ISSUE TITLE
Multiple NPC select

### ISSUE THREAD

**Issue by Galactic-dragon** [mcmonkey4eva/Sentinel#196]
Im pretty sure this may be supposed to be posted on citizens but im using this for sentinels sooo....
Can I select more than one sentinel at a time and give them the same command?
I found the squad command wich sounds like its the solution to my problem but I didnt find any commands to make it work other than it being listed in the /help menu I tried the command and it did nothing can you tell me how to use it/what does it do or any other command that allows me to give the same command to multiple sentinels at the same time?

**Comment by Galactic-dragon** [comment]
Sorry for the spelling errors

**Comment by mcmonkey4eva** [comment]
Nope :/ That'd be a request for Citizens if it were to be done...
