### ISSUE TITLE
add sponge support api 7

### ISSUE THREAD

**Issue by ziceptor** [mcmonkey4eva/Sentinel#198]
please!

**Comment by AnthonyAMC** [comment]
It wouldn't just be *adding* support... Sentinel would have to be completely rewritten since Sponge is a different platform. Also, Citizens hasn't been ported to Sponge yet.

**Comment by ziceptor** [comment]
Know. It is a reminder of the demand. :)

**Comment by mcmonkey4eva** [comment]
Will be done whenever Citizens itself is ported...

I don't really know the status of that, the Spongies were trying to make their own port which they stopped working at, the Citizens developer was going to port it 'properly' but is too insanely busy to work on it much...

**Comment by ziceptor** [comment]
Thanks for the info!
