### ISSUE TITLE
Ghast sentinels not attacking

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#199]
Hello,

When you put the "ghast" NPC type on a sentinel, it doesn't fire fireballs like ghasts, it just fly arround and does nothing. It would be nice to have this feature implemented so we could use Ghast-sentinels.

Thank you.

**Comment by mcmonkey4eva** [comment]
`/npc inventory`
Give it a weapon of your choice.
Fireball weapons are valid, as are anything else!

**Comment by Ferocimo** [comment]
We tried that but it didn't work : actually it seems there is a Citizens bug where you can't change the NPC's inventory when it's a ghast. So we changed the NPC back to human, equipped it with a blaze rod, and changed it again to a ghast, and it now fires fireballs. So it works now, thanks.
