### ISSUE TITLE
Replicate Sentry's KILLDROPS option

### ISSUE THREAD

**Issue by PsychoLynx** [mcmonkey4eva/Sentinel#20]
"If this is False any mobs the Sentry kills will not drop items or EXP." - Basically making it so, you can't stand next to an NPC sentry and reap the reward for doing nothing.

**Comment by mcmonkey4eva** [comment]
So an option on top of the existing drops control, to temporarily disable drops without clearing the dropped item list>?

**Comment by mcmonkey4eva** [comment]
okay so the Sentinel NPC killing mobs doesn't give drops... right, makes sense. Will add.
