### ISSUE TITLE
Sentinels able to hit through wall

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#200]
Hello,

As long as you are within range of a sentinel, it can attack you through any wall. That means that if you find a safe spot, but the sentinels still know that you are there (as they should), they will attack you through the wall instead of just waiting on the other side.

Demonstration : 
https://cdn-e2.streamable.com/video/mp4/mk5ze.mp4?token=1506006692_f371dc9f954b2584b79f952c4ac2aa5407cdecd6

If you could look into this that would be great, thank you.

**Comment by mcmonkey4eva** [comment]
Build DEV-154+ http://ci.citizensnpcs.co/job/Sentinel/ should fix this.
