### ISSUE TITLE
Question / Request: factionenemy

### ISSUE THREAD

**Issue by Rhutos** [mcmonkey4eva/Sentinel#205]
Hello,
in the outdated sentry plugin, there was a target pattern for the factions plugin: **FactionEnemy**
If you added for example: "**factionenemy: github**" all enemies of faction "**github**" would be targeted.
Currently it seems there only one way of support for factions (it isn't documented at least): To directly targeting or ignoring certain factions. So whenever a factions' relation changes, dozens of NPCs has to be changed as well.
The possibility to use "**factionenemy**" and "factionfriend" (for ignoring targets) would come very handy.

Thanks

**Comment by mcmonkey4eva** [comment]
Oo, I didn't think of that (Never used factions myself), but I'll add that soon!

**Comment by Rhutos** [comment]
That would be very nice!

**Comment by mcmonkey4eva** [comment]
Build DEV-150+ http://ci.citizensnpcs.co/job/Sentinel/ contains an attempt at this.

I can't really test as I don't have a server with several factions on it...

So, let me know how well it works!

**Comment by Rhutos** [comment]
:( Didn't work at all

(rising.json)
{
  "name": "ยง2Outlaws",
  "createdAtMillis": 1431647182238,
  "relationWishes": {
    "rising": "ENEMY"
  },
  "flags": {
    "permanent": true
  }
}

(outlaws.json)
{
  "name": "ยง9Rising",
  "createdAtMillis": 1431647182238,
  "relationWishes": {
    "outlaws": "ENEMY",
  },
  "flags": {
    "permanent": true
  }
}

(saves.yml)
targets:
  '0': MONSTER
ignores:
  otherTargets:
  '0': factionenemies:Rising
otherIgnores:
  '0': faction:Rising

**Comment by Rhutos** [comment]
Uhm, you got a typo: factionseneemy

**Comment by mcmonkey4eva** [comment]
OOPS. That's normally something I'd realize in testing >.>
I try to type carefully but that's just a really odd thing to type.
DEV-152 fixes that.
Sorry!

**Comment by Rhutos** [comment]
Yay! It works! :D

**Comment by mcmonkey4eva** [comment]
Great!

**Comment by Rhutos** [comment]
Btw: does factionsally include the faction itself?

**Comment by mcmonkey4eva** [comment]
I wouldn't know, that's dependent on whether Factions considers a faction to be an ally of itself.
Can test it and find out!

**Comment by Rhutos** [comment]
Hmm ignoring factions won't work at all:
Targets: PLAYER, MONSTER
Other Ignores: faction:rising, factionsally:rising

I will be attacked.

**Comment by mcmonkey4eva** [comment]
It has to be `factions:rising` not `faction:rising` - the s makes a difference.

**Comment by Rhutos** [comment]
Alright, thanks. So you have to write both ignores.
