### ISSUE TITLE
Guarding NPCs does not teleport when out of range?

### ISSUE THREAD

**Issue by Rhutos** [mcmonkey4eva/Sentinel#206]
In the outdated sentry plugin guarding NPCs teleported to target, when they got too far away.
Sentinels Guards seem to just be left behind. Is this an intended behavior?

/edit
Hmm something seems just really wrong.
My bodyguard is just ignoring every monster around me. And is moving to and fro. (an issue with citizens linear pathing?)

Targets: MONSTER
Ignored Targets: Owner (Which seems not to work at all)
Ignored Other Targets: faction:rising (mine) (Doesn't work as intended too - if I hit the npc, he's attacking me)

Craftbukkit 1.12.2
Citizens 2.0.22 (Build 1494)
Sentinel 1.4 (Build 146)

No error messages

/edit 2
Having waypoints and guarding a target at the same time, is causing the trouble.
Would be nice, if you could switch between area guarding and target guarding without removing the waypoints all the time ^^

Ignoring owner and factions still does not work for me tough (at least not for guardin area)

**Comment by mcmonkey4eva** [comment]
Build DEV-151+ http://ci.citizensnpcs.co/job/Sentinel/ contains a "first try" at solving this... I made it care less about path points when guarding a player. I don't know how much effect this will have. Try it, and let me know how it goes!

**Comment by Rhutos** [comment]
Didn't work :(
Still runs toward waypoints.

**Comment by mcmonkey4eva** [comment]
The fix was mainly in the direction of making it still attack enemies even when away from its waypoints.

**Comment by mcmonkey4eva** [comment]
Build DEV-153+ should fix running towards waypoints as well.

**Comment by Rhutos** [comment]
It works now :D

**Comment by mcmonkey4eva** [comment]
Wonderful!

**Comment by Rhutos** [comment]
But it still doesn't auto teleport, when pathing

**Comment by mcmonkey4eva** [comment]
It should teleport when it exceeds 60 blocks of distance.

Or does it get pulled back to a path point?

**Comment by Rhutos** [comment]
No, it's just stays there, where it's way is blocked. And it doesn't auto teleport, if you warp somewhere (like it does without waypoints)

**Comment by mcmonkey4eva** [comment]
It's likely being unfortunately blocked by the waypoint system somehow in a way pausing that couldn't prevent. Not much I can really do to my knowledge... short of hacking about with Citizens to remove the waypoints trait entirely and restore it later (not currently doable within the Citizens API, though).

Any fix would need to be done in Citizens, I believe.
