### ISSUE TITLE
centinel commands dont work ight in command blocks.

### ISSUE THREAD

**Issue by ScuroK** [mcmonkey4eva/Sentinel#207]
Hi here is my problem with command blocks.

For example:
I need 2 command block to do 
1: /npc select 123  ->works
2. /sentinel respawn -> does not work. command block tells me i should make sure i did /trait sentinel

But the npc "123" IS a sentinel!

This is very important for quests and adventures. could you fix this maybe?

<3

**Comment by ScuroK** [comment]
same goes with /execute in command blocks. doesnt matter :/

**Comment by mcmonkey4eva** [comment]
Command blocks cannot properly select NPCs.
Consider doing a quick Denizen script to be run by the block.
( https://www.spigotmc.org/resources/denizen.21039/ )
