### ISSUE TITLE
Drops are failing

### ISSUE THREAD

**Issue by CorporalBruno** [mcmonkey4eva/Sentinel#21]
Set drops to npc with sentinel trait.

Verify the drops are there after closing inventory graphical user interface.

Kill sentinel.

No drops.

**Comment by mcmonkey4eva** [comment]
Do you perhaps have any plugins/scripts that disable death drops for anything?
I replaced the old "forceful" drop code with just replacing the events' drops with the correct items.

**Comment by mcmonkey4eva** [comment]
Was confirmed on IRC to be a plugin fault - either way, added a workaround option to the config for this :) https://github.com/mcmonkey4eva/Sentinel/commit/20a2bd5675b542ee294315641f154fa4c632a76a
