### ISSUE TITLE
Backend API connection?

### ISSUE THREAD

**Issue by xwingevents** [mcmonkey4eva/Sentinel#210]
I was wondering if I could edit the trait directly with my code? I am coding a unique server which will utilize NPC Sentinels and allow them to be upgraded via a GUI. So i am wondering how I can modify the object directly instead of console commands.

**Comment by mcmonkey4eva** [comment]
Link Citizens2 and Sentinel as APIs with maven.
Both available via the Citizens repo.

You can then do `npc.getTrait(SentinelTrait.class)` to get a valid SentinelTrait object, and with that configure freely.
