### ISSUE TITLE
Sentinel maximum health ?

### ISSUE THREAD

**Issue by Hizarion** [mcmonkey4eva/Sentinel#211]
I don't know how to change the maximum health a sentinel can have. The maximum is actually 2000 and I have uped the maximum health on my spigot.yml to 9999 but a the maximum of a sentinel still at 2000... How can I change it ?

**Comment by mcmonkey4eva** [comment]
As best I'm aware, Spigot does not expose this value to the Bukkit API 0.o
so I've had to lock it in to 2000 pending a method of figuring out via the API what custom value (if any) is added there.

**Comment by Hizarion** [comment]
So I can't do anything ? Because with sentry I could change the health of an NPC  above 2000. (sorry if I've missunderstood, I'm french so my english is quiet mediocre)

**Comment by mcmonkey4eva** [comment]
I'll probably add a Sentinel config option to let you specify what Sentinel views as the max health.

**Comment by mcmonkey4eva** [comment]
Added to latest dev build (DEV-156) at  http://ci.citizensnpcs.co/job/Sentinel/

Delete your `config.yml` from Sentinel, let it respawn, then edit the value:
```
    # The maximum health value for any given Sentinel NPC.
    max health: 2000
```
under the `random:` block

**Comment by Hizarion** [comment]
Thank you man you are amazing ! :D
