### ISSUE TITLE
[BUG/Request?] Attacking Sentinels while Player is Invisible

### ISSUE THREAD

**Issue by Formula350** [mcmonkey4eva/Sentinel#212]
Running on Sentinels build 156, Citizens build 1494, Spigot v1.11.2

Players who are invisible, but wearing armor --thus, still visible, in reality-- are able to attack the NPC without getting attacked. This would be understandable if either the player had no armor on, leaving them completely invisible.

The suggestion/s, if possible/not too complex, are:
- Have a check where it will ignore the invisible player ONLY when they have do *NOT* have armor on. If they put armor on, it will immediately see them and begin attacking.
- If  that's too difficult, perhaps have it so that they will be seen and able to be attacked after THEY attack (Possibly being able to 'see' them for 10 seconds after the player lasted attacked, permitting them to sneak up on them once again if they want)
- If nothing else, have a config option so that the Sentinels completely ignore player invisibility, and attack anyways, like Sentry did.

Overall, Sentinels have been a fair upgrade from Sentry, but a couple things (like this) have definitely made the change over from Sentry difficult. This one particularly since it allows players to just wail on a really powerful Sentinel all while the player doesn't take a single hit. :\

Thanks,
-Formula350

**Comment by mcmonkey4eva** [comment]
Try new build (DEV-157+ http://ci.citizensnpcs.co/job/Sentinel/ ),
It features... well, all three options you just listed.
- Armor disables invisibility
- A config option
- Attackers are considered visible

----

I thought I already had a config option for that, woops!

**Comment by Formula350** [comment]
Wow what a great coincidence, or quick turn around hah Either way, thanks, I'll let you know! :)

**Comment by Formula350** [comment]
Yep that did it. Thank you!
