### ISSUE TITLE
Npc nagivation

### ISSUE THREAD

**Issue by bremsun** [mcmonkey4eva/Sentinel#220]
npc.getNavigator().cancelNavigation();
npc.getTrait(SentinelTrait.class).npcNameTargets.clear();
npc.getNavigator().setTarget(newloc);

Here's how i try to move my npcs, but when this is called, the npc will just move and freeze when sentinel refresh every 10 ticks, so i have to call the function twice to actually tell them to move to where i want.

**Comment by mcmonkey4eva** [comment]
The idea of Sentinel is it has its own AI. You either have to shut that off or use an acceptable override. The latter would be using the "/npc path" waypoint system (accessible via API code as well of course) to make it move. Which is only there to allow users to make "patrol" Sentinel NPCs.

**Comment by bremsun** [comment]
thx :)
