### ISSUE TITLE
NPC unable to attack if target keeps walking?

### ISSUE THREAD

**Issue by MedicOP** [mcmonkey4eva/Sentinel#221]
Every time the NPC is within 3 blocks range of the target, he stands still to swing his sword, but it never actually happens if the target keeps walking, because the NPC won't have enough time to swing before the target is too far away already. So it's just an endless chase without any attacking

**Comment by MedicOP** [comment]
It can be fixed by increasing updatePathRate and attackRange

**Comment by Midnight9746** [comment]
You could of also increase the npc's speed to catch up (you can use like speed 1.5 I think) because the problem I see from changing the rate, is that it will hit faster when you don't run from it.
