### ISSUE TITLE
Increase HP of NPC

### ISSUE THREAD

**Issue by AdraliK** [mcmonkey4eva/Sentinel#223]
I want to have HP on NPC was not in 2000. For example 10000.

**Comment by mcmonkey4eva** [comment]
There's a config option for that (note that you also have to adjust spigot settings as well)

**Comment by AdraliK** [comment]
And you can tell because in the config I found nothing. Version of config is 8

**Comment by Midnight9746** [comment]
I too would like to know how do change this. :)

**Comment by mcmonkey4eva** [comment]
Spigot and Sentinel config both have a max health value option, both can be adjusted per need (just remember that the Spigot one must always be more than or equal to the Sentinel one!)
