### ISSUE TITLE
npc doesn't not return

### ISSUE THREAD

**Issue by madtomic** [mcmonkey4eva/Sentinel#228]
npc doesn't not return to spawn point after chasing a player

**Comment by mcmonkey4eva** [comment]
The spawn point is where it goes when it's died. If you want a guard area to return to, set a point with `/npc path`

**Comment by Midnight9746** [comment]
As mentioned, you have to enter /npc path, after you select the npc and then left click the ground where you want it to go to. Now when it chases the player, it should run back to that spot. If it can't pathfind it's way back, it will tp.
