### ISSUE TITLE
Permanent glow effect

### ISSUE THREAD

**Issue by Pepyto** [mcmonkey4eva/Sentinel#229]
Hi !
I gave a spectral arrow to an npc, but of course, now, players have the glow effect on them.
But, I cannot remove it.
- /effect clear
- Restarting the server

If you have an answer, it could really help me :'(

See you
Pepyto

**Comment by mcmonkey4eva** [comment]
I'm not sure of the Minecraft built-in command but using Denizen ( https://www.spigotmc.org/resources/denizen.21039/ ) it'd be `/ex adjust <player> glowing:false` ... when using on another player, you can do `p@othername` instead of `<player>`

**Comment by Pepyto** [comment]
Hi there !
It's me again.
I took Denizen's plugin, and when I executing the command in game, I've got this error :
Executing dCommand... check consol for debug output

So I checked the console 👍  ... Well ..

> Pepyto issued server command: /ex adjust Grocalin glowing:false
> [19:51:41] [Server thread/INFO]:  Starting InstantQueue 'EXCOMMAND_CeoHiredConvicted'... 
> [19:51:41] [Server thread/INFO]:  Queue 'EXCOMMAND_CeoHiredConvicted' Executing: ADJUST 
>                    "Grocalin" "glowing:false" 
> [19:51:41] [Server thread/INFO]: +- Executing dCommand: ADJUST/p@Pepyto ---------+ 
> [19:51:41] [Server thread/INFO]: +> Executing 'ADJUST': object='Grocalin'  mechanism='glowing'  
>                    mechanism_value='false' 
> [19:51:41] [Server thread/INFO]:  ERROR! Unfetchable object found 'Grocalin'! 
> [19:51:41] [Server thread/INFO]:  Completing queue 'EXCOMMAND_CeoHiredConvicted' in 4ms. 

So I don't know where is the mistake !? Hmm, is that because I need to create a script ? Don't think so ..

The server is in 1.10.2.

If you have a solution ^^

See you !
Pepyto ~

**Comment by mergu** [comment]
> when using on another player, you can do `p@othername` instead of `<player>`

**Comment by Pepyto** [comment]
I did it too. Same problem ;)

**Comment by mcmonkey4eva** [comment]
You wrote the username but you didn't follow the format (using `p@`)

**Comment by Pepyto** [comment]
Here it is ..
When I follow the format p@, it stills not working.

>  Pepyto issued server command: /ex adjust p@IPinPin glowing:false
> [21:28:01] [Server thread/INFO]:  Starting InstantQueue 'EXCOMMAND_NavGenealogyInches'... 
> [21:28:01] [Server thread/INFO]:  Queue 'EXCOMMAND_NavGenealogyInches' Executing: ADJUST 
>                    "p@IPinPin" "glowing:false" 
> [21:28:01] [Server thread/INFO]: +- Executing dCommand: ADJUST/p@Pepyto ---------+ 
> [21:28:01] [Server thread/INFO]: +> Executing 'ADJUST': object='p@IPinPin'  mechanism='glowing' 
>                     mechanism_value='false' 
> [21:28:01] [Server thread/INFO]:  ERROR! Entity referenced is null! 
> [21:28:01] [Server thread/INFO]:  Completing queue 'EXCOMMAND_NavGenealogyInches' in 2ms.

**Comment by mcmonkey4eva** [comment]
Do note it only works for online players

**Comment by Pepyto** [comment]
The player is actually in front of me :'(

**Comment by mcmonkey4eva** [comment]
Either something went wrong with version matching, the player name given is not valid as an online player, or you have corrupted player data. (EG if your server has ever been run in offline mode)

**Comment by Pepyto** [comment]
Problem solved.
Because we ran the server in offline mode once .. And yup, corrupted player.
So I op the player, and he did that command, word for word
/ex adjust <player> glowing:false

And it worked !

Thank you so much for this after-sales service (without sales)
Good luck !
