### ISSUE TITLE
Fightback seems to not care about the setting (0.5) / Possible timer add on?

### ISSUE THREAD

**Issue by Nutty101** [mcmonkey4eva/Sentinel#23]
The fightback seems to keep attacking if you attack the NPC (True or False).

Also would it be possible to set a limit on how long the NPC will continue to target the user? Say 10 seconds and it will no longer target them after being attacked? Something we could set would be cool.

**Comment by mcmonkey4eva** [comment]
What's wrong with "Target them until we take the aggressor out"?

**Comment by LoreCase** [comment]
We have a jailer plugin, the plugin would teleport a player to the jail right before they die. The npc continues to viciously beat at the player until  they are dead regardless. Isnt that a bit off.

**Comment by mcmonkey4eva** [comment]
Faaaiiiirrr enough.

**Comment by Nutty101** [comment]
Though, I do like the permo punishment part :)
