### ISSUE TITLE
Health, Guard, & Rpg Item Intergration Request

### ISSUE THREAD

**Issue by Midnight9746** [mcmonkey4eva/Sentinel#230]
A few things, 

Health:

I was wondering how one goes on about increasing the npc's health, as in #223 it was said that in the config I can do this and also in spigot's yml. Yet issue was locked without mentioning what exactly needed to be changed.

Guard:

When a player tps away from the npc and the chunk unloads, their guard stays put until that chunk is revisited by the player (or another comes along, activates it and it tps back to its owner) Is there a way to keep guard's chunk always active to prevent this?

Rpgitem Request:

Using Rpgitem's item/armor settings with the sentinel

This might relay on citizen's plugin but -shrug- I say that because I'm not sure if it uses citizens inventory.

What I'm wanting to do is equip npcs with Rpg items to give the npc abilities and effects. 

Example:

Golden Chestplate
Armour: 25%
Gives speed
Gives off particles when held (or worn)

When I put that in the Sentinel npc at first, it seems to load the armor's protection value (the 25%) so when a player hits it with an rpg sword, they don't easily drill though the npc. (Health drops quicker and I don't want the armor to break) but it doesn't give it speed or show the particles.

When I left and came back, the sentinel started to ignore the armor and it became pretty much a normal golden chestplate. 

Inventory / Item Switch:

Something that I just remembered, how do I get an sentinel to switch items? I give it a sword and it won't let me give it a bow without changing the items and when I use the Sentinel inventory command it won't let me add both items.

**Comment by mcmonkey4eva** [comment]
Health - look through the relevant config files. It shouldn't be hard to find. I just glanced in the Sentinel config and found it very quickly without remembering where it was (it's labeled clearly and has a description info line above it... and there's not that many options that you can't just read through them all).

Guard - There is an option in Citizens config to keep an NPC's chunk loaded. Though also, if it doesn't teleport properly that will need to be handled in a Sentinel code update, as that's a bug.

RPGItem - That's a case of the plugin powering those options needing to account for NPCs intentionally. Can't do anything useful from Sentinel-side short of duplicating that entire plugin within Sentinel. If NBT Attributes are lost on NPC respawn, there might be something failing to save/reload correct in Citizens. Make sure you're running the latest dev build of Citizens and if there's a clear loss of actual on-item data, report that on the Citizens page.

Inventory - You give all the additional items through the inventory (just put items in spare open middle-row-ish slots). It can be a bit glitchy, especially on older versions. Definitely make sure you're up to date there.

**Comment by Midnight9746** [comment]
Health - Eh I found both health values but the server sees the 2048 value for players only, and the sentinel's health is "what should this npc spawn with?" which works (and is lower than spigot), however it's a one time set, any health value still cannot exceed 2000.

Guard - Thanks, this has been fixed! :)

Rpgitem - Understandable, heh.. just thought it would be cool

Inventory - I figured out a non-glitchy way, add the bow and sword before giving them the trait. My sentinel is now using a bow/sword

**Comment by mcmonkey4eva** [comment]
`any health value still cannot exceed 2000` if that is happening it's not a limit from Sentinel. From what I can see there are no health control calls anywhere that cap at anything other than current max health on the NPC or config granted global max health.

The way you wrote that makes me concerned that you may have edited entirely the wrong value in the Sentinel config. I again urge you to actually read through the provided options. The default spawn health value (of 20 when unmodified) is not the config option to change...

**Comment by Midnight9746** [comment]
All that I see: https://pastebin.com/dBc0dGiV

**Comment by mcmonkey4eva** [comment]
Your config is outdated. https://github.com/mcmonkey4eva/Sentinel/blob/master/src/main/resources/config.yml#L62

**Comment by Midnight9746** [comment]
Thank you! :)

**Comment by Midnight9746** [comment]
Problem is solved still, just wanted to state: I downloaded the version off of spigot just now. What I had was version 1.4, spigot had 1.4.5.

**Comment by Midnight9746** [comment]
> Problem is solved still, just wanted to state: I downloaded the version off of spigot just now. What I had was version 1.4, spigot had 1.4.5.

Yeah okay, what I failed to do was to regenerate my config file to make sure that the new version is loading that option. Currently for me, 1.4.5 is loading the old config. Thus the new health isn't talking affect.

I feel bad for reopening this.

**Comment by mergu** [comment]
Join our discord: https://discord.gg/Q6pZGSR

**Comment by Midnight9746** [comment]
That be great an all if I didn't get locked out of that... _I'm waiting on Discord to help me with that since it was 2 stepped and they have to take a month to delete and such._ I don't want a new email.

So eh see you guys in a month... :/

**Comment by mergu** [comment]
We also have an IRC where we can help, it's broadcast to the Discord:
https://one.denizenscript.com/ircchat_denizen

**Comment by mcmonkey4eva** [comment]
Run latest Sentinel: http://ci.citizensnpcs.co/job/Sentinel/

**Comment by Midnight9746** [comment]
Okay now it's all fixed. Thanks!
