### ISSUE TITLE
Support CrackShotPlus recoil

### ISSUE THREAD

**Issue by bc-hill** [mcmonkey4eva/Sentinel#231]
[CrackShotPlus](https://www.spigotmc.org/resources/%E2%96%91-crackshotplus-%E2%96%91-1-8-x-1-12-x-%E2%96%91.18085/) (an addon for [Crackshot](https://www.spigotmc.org/resources/crackshot-guns.48301/)) adds recoil with it's weapons.

I am finding that when my Sentinel uses one of these weapons, it (understandably) does not account for the recoil.  So, it is possible for a Sentinel to send himself backwards off of a cliff while firing.

Would it be possible for Sentinel to somehow compensate for the recoil?

Thank you.

**Comment by mcmonkey4eva** [comment]
I by policy refuse to support "premium only" plugins in any manner from within a free and open source project.

You've apparently paid that developer for that project, maybe ask that developer to add handling within it (EG by just not giving recoil effects to an NPC).

**Comment by bc-hill** [comment]
Thank you.
For future reference, I just needed to set a single waypoint for the NPC, to get him to hold still.
