### ISSUE TITLE
Sentinels Won't Follow Attackers

### ISSUE THREAD

**Issue by Midnight9746** [mcmonkey4eva/Sentinel#232]
I don't see any console errors, the plugin and server is up to date (I think), but what it's doing is that when I stand within 3 blocks, the NPC will attack / fight back. But none of them will follow me (or even walk on their own) when I walk away. I tried the range, chaserange/close, speed, anything I could think of. They worked before, so I'm not sure why they broke now. I looked into path finding, and things like that, nothing seems to affect it.

>Also might be related, new NPC won't load skins at all, even when it's set to mine. All the created ones load just fine, but changing their skins or a newer one's gives me a steve or alex even after a server restart. Although this might not even be Citizens, as giving myself a player skull is totally buggy and won't load the skin either, and gives me all lowercase skulls. So this part might just be compatibility with a plugin like ProtocalLib. 

Edited: I logged in today, the skins are working now. NPC's still won't follow.

Versions:
Citizens - 2.0.22-Snapshot B1505
Sentinel - 1.4.5 B160
Server - 1.12.2 (0 versions behind)

**Comment by mcmonkey4eva** [comment]
All Sentinels? Previously functioning ones that now don't? Only new ones? Only specific ones? If things functioned before but stopped, what changed between then and now?

**Comment by Midnight9746** [comment]
All sentinels who aren't set to guard a player. Those ones will follow the person they are guarding and will attack anyone who hits that player. But all the other npcs only hit when you come within range. 

Things that had changed was new plugins, I ran the server without those changes and it still happend.

**Comment by mcmonkey4eva** [comment]
... Did it work before and then stop working with "new plugins"?

If so, figure out what got changed at that time.

Maybe some plugin even modified a setting somewhere that has disabled NPC attack movement.

**Comment by Midnight9746** [comment]
What I'll go do is just run a test server with just sentinel and citizens to see if they run

**Comment by Midnight9746** [comment]
I don't think it's the new plugins because they are all compatible with citizens and sentinel and I've seen many servers where they all ran together.

**Comment by mcmonkey4eva** [comment]
Pushed a patch to build DEV-162+ on http://ci.citizensnpcs.co/job/Sentinel/

It should make teleportation handling more stable. Let me know if it works for you!

**Comment by Midnight9746** [comment]
In the meantime, I found out that the Npc skin bug is because skins.minecraft.net site is having it's ups and downs. Which sadly when it's down, it won't render new skins on the npcs until it's back up.

This annoyingly also affects things like the Magic plugin, Dynmap, and everything using that website to load skins.

Just letting you know that it's not your plugin, just incase you didn't know.

I'm going to close this issue right now, only because I'm pretty sure that build is gonna work. If not, I can always reopen it. (I've been busy so haven't found time to update it, and it's also not critical :P)

**Comment by Midnight9746** [comment]
@mcmonkey4eva It's fixed now, just NPCs go invisible when they enter the Nether and End. Until a reload. But I think that's normal.

**Comment by mcmonkey4eva** [comment]
Might be a Citizens issue there, they shouldn't just go invisible on a cross-world teleport.

**Comment by Midnight9746** [comment]
Citizens might be outdated lol... it's on 2.0.22-SNAPSHOT Build: 1505
