### ISSUE TITLE
Sentinel attacks players even when in spectator

### ISSUE THREAD

**Issue by MrDienns** [mcmonkey4eva/Sentinel#233]
Title says it. On my server I have this NPC that gets triggered when you hit him. When you then go into spectator mode, the NPC doesn't go away or anything, it just keeps smashing the air where you're flying. I believe this is a bug and it should simply act like the player is not there.

https://gyazo.com/2d3d59bceae66e0e40f68a194256236a

**Comment by mcmonkey4eva** [comment]
Patched for build DEV-161+ on http://ci.citizensnpcs.co/job/Sentinel/

Thanks for the report!

**Comment by MrDienns** [comment]
Amazing! I will test it out right now.
