### ISSUE TITLE
get if you are close to a npc

### ISSUE THREAD

**Issue by Wqrld** [mcmonkey4eva/Sentinel#238]
i basicly want my plugin to say: guarded when you are close to a guard npc, is there a api for this or do i have to manually check if there are any guards nearby

**Comment by mcmonkey4eva** [comment]
Uh... loop through the list of spawned NPCs (provided by Citizens), check if they're in range of the player (a simple distance check + any other logic you might want), and check the SentinelTrait on the NPC (check hasTrait, and then if so read the trait and check any values that might distinguish it as a guard or an unrelated Sentinel NPC).
