### ISSUE TITLE
Sentinel => 1.8 ? :/

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#24]
Hello ! c:

Can you add compatibility with 1.8 ? (Spigot)

Thanks.

**Comment by mcmonkey4eva** [comment]
Why.

**Comment by Blamo27** [comment]
Because I'm on it. :(

**Comment by mcmonkey4eva** [comment]
Update then.

**Comment by Blamo27** [comment]
> And because of compatibility problems we can't go on 1.9 yet

**Comment by mcmonkey4eva** [comment]
Compatibility with what?

**Comment by Blamo27** [comment]
Well, firstly and most importantly, with players. A lot of them does not want to play on 1.9, our server is a solution for them.

**Comment by mcmonkey4eva** [comment]
Lol. So, in short, you and your playerbase hate new things.
Therefore, they do not want new plugins.
Therefore, I have no reason to attempt to backport Sentinel :)

**Comment by Blamo27** [comment]
Not wanting to update to 1.9 does not equal hating new things. It just equals listening to our players, players who don't like some of the new features of 1.9. It doesn't mean they hate ALL new things. But obviously you don't want to do that for personal reasons, which I can understand, I think. Thanks anyway.
