### ISSUE TITLE
FactionsUUID Support

### ISSUE THREAD

**Issue by HyperVx2** [mcmonkey4eva/Sentinel#241]
It would be nice if this also supports [FactionsUUID ](https://www.spigotmc.org/resources/factionsuuid.1035/)or [FactionsOne](https://www.spigotmc.org/resources/factionsone.9249/).

**Comment by mcmonkey4eva** [comment]
We support https://www.spigotmc.org/resources/factions.1900/
Any other plugin claiming to be Factions should have compatible API, and if not, it's they're fault for the incompat and up to them to fix it.
FactionsUUID will not be supported directly at all. It is extremely difficult and extremely pointless for a free and open source project to try to link into a "premium" API.
