### ISSUE TITLE
Magic spells are passing through Sentinels

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#242]
Hello,

Magic (<a href="https://www.spigotmc.org/resources/magic.1056">Magic</a>) spells are passing through Sentinels without causing any damage like you can see in this video below :
https://cf-e2.streamablevideo.com/video/mp4/ibio0.mp4?token=1523199630-Pq%2BVcf%2BEIZycls711%2BkF01bzjevyf3O04Dp8iTqtyY4%3D

Our Sentinel configuration : <a href="https://gist.github.com/Blamo27/f75229a81caf9fdb4bed0e7d04329f5e">Sentinel configuration gist</a>

Can you check that please ?
Thanks.

**Comment by mcmonkey4eva** [comment]
That is not a solid entity, that's a particle effect with damage / impact / etc. logic 100% local to the "Magic" plugin. It's up to them to explicitly support NPC targets.

You may be benefited from toggling settings like "`/npc playerlist`" which may increase the chances of the plugin believing that NPC to be a real player target.

**Comment by Blamo27** [comment]
@mcmonkey4eva Okey thanks, I created a new issue on the Magic GitHub

**Comment by NathanWolf** [comment]
Magic does not target NPCs by default.

You can change this in the config, but I’m wondering - is there a simple way (metadata?) to differentiate between a Sentinel and other NPC?

**Comment by mcmonkey4eva** [comment]
@NathanWolf there's no reason to. If the NPC accepts damage, damage it.

**Comment by NathanWolf** [comment]
I am currently doing nothing more complex than checking for “NPC” metadata.

The majority of users have asked for spells to ignore NPCs. It’s not just about damage, it’s about pushing them around. Most people don’t use NPCs this way, it’s really just Sentinel that changes the dynamic of what an NPC is used for.

**Comment by mcmonkey4eva** [comment]
Citizens has its own data helper (`npc.data()`) that most info is on. If you're able to hook into Citizens, using that and checking against `NPC.DEFAULT_PROTECTED_METADATA` would suffice (default value for it is `true` for reference). If it is `true`, the NPC is an invulnerable static NPC. If it is `false`, the NPC is able to take damage and be pushed around. These are checked against to ensure that standard Minecraft-given push/damage/etc. calls are blocked appropriately.
If possible at all, I would suggest ensuring damage/pushing calls are done through standard calls. Where not possible, a direct Citizens hook would be ideal. Might be other ways to test for that but I'm not sure offhand.

**Comment by NathanWolf** [comment]
Thank you for that info! I will take a look and consider adding some better integration, I already have custom traits so it shouldn’t be a problem.

I have found that checking for entity metadata is surprisingly expensive, maybe this will be a performance improvement as well?

For what it’s worth I am just using Entity.setVelocity to push entities around, so it’s odd that works on NPCs, by the sound of it. Maybe it doesn’t, it’s been a long time since I turned NPC targeting on in my own plugin.

**Comment by mcmonkey4eva** [comment]
setVelocity is not restricted, as that's not a minecraft call, that's a Bukkit call (which doesn't interact with Minecraft's checking). Minecraft calls in this regard would be the logic path that fires when a player stands in the NPC's spot and it gets slowly pushed back, which is an entirely separate thing from setVelocity, which basically just edits the velocity value without verifying validity (on the assumption that the plugin calling it really does want that to happen).

Also yeah Bukkit entity metadata is concerningly weird in implementation and using a simpler call (that can be shortened to a single boolean check when Citizens hook is disabled) will very likely be a lot faster.

**Comment by NathanWolf** [comment]
Awesome, sounds totally worth doing then. Thanks!
