### ISSUE TITLE
Guards moving back to setspawn point after fight

### ISSUE THREAD

**Issue by GoodGuyGriz** [mcmonkey4eva/Sentinel#243]
I would be really helpful if there was a system were when they are done chasing/killing something they would go back to the marked spot. I have currently Sentinels everywhere in my town when they were supposed to be at the gate. Besides that, I really dig the plugin/mod

**Comment by GoodGuyGriz** [comment]
When I type that command it says ``You're already in an editor!``

**Comment by mcmonkey4eva** [comment]
You're already in an editor then? Close that editor, then continue.
Relevant to know basic Citizens usage - some commands like `/npc text`, `/npc equip`, `/npc path`, etc. involve an editor lock, that you have to remember to close after you're done.
Mostly these involve non-command inputs as well, EG `/npc path` works by clicking in the world when the editor is opened.

BTW: Open issues direct on GitHub, please do not read or reply by email.
