### ISSUE TITLE
Ignore unreachable targets

### ISSUE THREAD

**Issue by doitliketyler** [mcmonkey4eva/Sentinel#25]
I have a Sentinel in my spawn that is going nuts because there is a zombie below him that they can't actually get to. Is there anyway to have the Sentinel ignore unreachable targets?

**Comment by mcmonkey4eva** [comment]
It shouldn't be doing that at all 0.o -- there's a CanSee check, which minecraft may be filling incorrectly? I'll look into this.

**Comment by mcmonkey4eva** [comment]
Fixed! Thanks for the report :)

**Comment by doitliketyler** [comment]
Great! Thanks for speedy fix :)
