### ISSUE TITLE
Shield activate NPC

### ISSUE THREAD

**Issue by rotus1122334455** [mcmonkey4eva/Sentinel#250]
Hi
I would like a way for making the Players of my server (that have a army thanks to your plugin)
be able to make their NPC soldiers use shields .

I think it would be cool a command with : /useshields     

info : Citzens2 says it would be possible with the api : PlayerAnimation#START_USE_XXX_ITEM

Like that the players of my server could make epic fights with their armys AND WITH SHIELD WALLS!
https://media-cdn.tripadvisor.com/media/photo-s/0f/fc/4a/69/shield-wall.jpg

**Comment by mcmonkey4eva** [comment]
If you want automatic shield handling, that's discussed in https://github.com/mcmonkey4eva/Sentinel/issues/70

If you want a command to raise/lower shield: That's not something for Sentinel to add. You might use Denizen for that (like `/ex animate <npc> animation:start_use_offhand_item`)

**Comment by rotus1122334455** [comment]
Thanks for reply
How can I do mass select ?

Is there any way to select multiple npc's just by right clicking the npc you made : Like this plugin https://www.spigotmc.org/resources/faction-mobs.15803/

**Comment by mcmonkey4eva** [comment]
Not in Citizens, but you can create a list of NPCs to apply commands to in Denizen
