### ISSUE TITLE
Feature Request: Kingdoms+ Integration

### ISSUE THREAD

**Issue by Velinquish** [mcmonkey4eva/Sentinel#251]
It would be great if [Kingdoms+](https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-8-1-12-2.11833/) Kingdoms could also be added to the list of targets so Sentinels can be set to ignore a Kingdom or target a specific one.

**Comment by mcmonkey4eva** [comment]
Can only build for free+open source plugins. Premium won't work.
