### ISSUE TITLE
How to make NPCs attack entites outside of it's squad.

### ISSUE THREAD

**Issue by TheRealWHfan** [mcmonkey4eva/Sentinel#255]
I have spigot 1.12.2
I have citizens-2.0.22-SNAPSHOT
I have sentinel-1.5.0

**Comment by mcmonkey4eva** [comment]
Er...
Is this meant to be a request to have a way to make NPCs target a specified squad? (Like, `/sentinel addtarget squad:baddudesquad`)
(Guessing based on Discord chatter that led to you posting this)

**Comment by TheRealWHfan** [comment]
Oh I found the /sentinel squad SQUAD - Sets the NPC's squad name (null for none). so I thought I could target other squads because I saw the sbteam:SCOREBOARD_TEAM_HERE. Well I guess that's not a feature so how do I make a npc target a certain scoreboard team in java code?

**Comment by mcmonkey4eva** [comment]
Added in build DEV-176+ on http://ci.citizensnpcs.co/job/Sentinel/
