### ISSUE TITLE
[Request] NPC AI improvements

### ISSUE THREAD

**Issue by WhyDoWeWonder** [mcmonkey4eva/Sentinel#258]
The output of command `/version` on my server is: **TacoSpigot-b23f17ef**
The output of command `/version citizens` on my server is: **(2.2.0.22-SNAPSHOT (build 1540)**
The output of command `/version sentinel` on my server is: **1.5.0**

Request

Have the NPC's only follow you in a straight line when it is necessary to get through a path, not everywhere you go. It looks really weird with 5 of them following you from the exact some block, and it's an ez target for AoE attacks.

**Comment by mcmonkey4eva** [comment]
Neat feature to have.
I think a bare minimum solution to this would be:
Whenever an NPC following you needs to catch up to you (based on following range), it should select a random spot between you and it in range - allowed to be offset in any direction (including specifically off to the side), as long as it doesn't make it run past you or annoyingly close to you.

**Comment by mcmonkey4eva** [comment]
Fixed in build DEV-175+ on http://ci.citizensnpcs.co/job/Sentinel/
