### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HyperDioxide** [mcmonkey4eva/Sentinel#26]
I have a suggestion, 
Would it be possible to make these sentinels use particle effects to attack? Perhaps a config option where you can choose the particle name
the amount, the range, the dmg, etc! It would a really amazing dynamic to your plugin!
I compeletly understand if you think it's a bad idea or 
you don't have much time for it!

**Comment by mcmonkey4eva** [comment]
This seems like a job for a separate plugin, that Sentinel would then link to...
