### ISSUE TITLE
Players not taking knockback against Sentinels

### ISSUE THREAD

**Issue by Ferocimo** [mcmonkey4eva/Sentinel#261]
Versions :
http://www.noelshack.com/2018-35-7-1535879690-2018-09-02-11-14-21.png

Hello,

I don't know for how long this issue has been there (maybe forever) but we only noticed recently : players don't take knockback at all from being hit by Sentinels (melee or ranged).

Thank you for looking into this.

**Comment by mcmonkey4eva** [comment]
Luckily I've interacted with your group recently enough to remember:

You have a wildly non-standard config, and that issue is definitely caused by that weird config.

Can you please pastebin your current config file?

**Comment by mcmonkey4eva** [comment]
I suspect you have `workaround damage` false and `enforce damage` true.
I've applied an update to Sentinel @ https://github.com/mcmonkey4eva/Sentinel/commit/31caf160c61ba9a3c7c64a873e5e1d9ea19de692
Build DEV-182+ on http://ci.citizensnpcs.co/job/Sentinel/ contains this fix.

**Comment by Ferocimo** [comment]
This is correct, we have these options set like you described, out of necessity against other issues.
We'll update and test again, thank you for your reply.

**Comment by mcmonkey4eva** [comment]
Build DEV-186+ contains a fix.

I should have seen that coming, lol. The knockback code was a bit loose.

The new version will apply less knockback force the faster a target is already moving (So multiple knockbacks in a row will do significantly less movement speed). I also applied a loose damping effect to the existing velocity, which is similar to what Minecraft does natively.

I think the actual native Minecraft knockback algorithm entirely removes any existing motion force, which is pretty meh. I think this code should be very similar in result, but a bit nicer in some edge cases.

**Comment by Ferocimo** [comment]
Seems to work fine now indeed, thank you very much for the quick answers !
