### ISSUE TITLE
Sentinel Accuracy

### ISSUE THREAD

**Issue by iamcion** [mcmonkey4eva/Sentinel#263]
The output of command `/version` on my server is: Craftbukkit version git-Spigot-7754231-94b0980 (MC: 1.12.2)
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT (build 1568)
The output of command `/version sentinel` on my server is:version 1.5.0 (build 170)
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/PfnMJA0b

Alright, so first of all my saves.yml file link is: https://pastebin.com/pPaaRVrx

Secondly the accuracy offset is 0 for my NPC and the arrows are not accurate, they fly all over the place.

**Comment by mcmonkey4eva** [comment]
Can you explain exactly what's going wrong?
And/or post screenshots or video of the way they shoot in-game?

**Comment by iamcion** [comment]
Nevermind.. fixed the issue
________________________________
