### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by HollishKid** [mcmonkey4eva/Sentinel#28]
Hello, 

I'm running CraftBukkit version git-Spigot-4af49dc-23da8b0 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

alongside with citizens and sentinel.
I get the following error literally spammed in console:

http://pastebin.com/A3taT1tZ

Any thoughts on this?
Thanks!

**Comment by mcmonkey4eva** [comment]
Update: http://ci.citizensnpcs.co/job/Sentinel/

**Comment by HollishKid** [comment]
I reopen this issue to tell you that even with build #37 of Sentinel I still get the same error spammed in console.
Using latest Citizens (build #1367) and Spigot 1.9.4.

**Comment by mcmonkey4eva** [comment]
I highly doubt the exact same error is there. If nothing else, line numbers should move. Can you please post the updated error message?

**Comment by HollishKid** [comment]
Here it is

http://pastebin.com/yxA4R4Fb

**Comment by mcmonkey4eva** [comment]
I've pushed a new build that will handle this error far more gently. The error itself appears to be somewhere on your end, unfortunately. The NPC, after being killed, has a null location storage value (it doesn't know where it was when it died, and it doesn't have a spawnpoint) - I don't know why this would happen, unless a world got unloaded/deleted or something.
Build 38 contains the gentler warning. Who knows, perhaps it'll show up only once and never again if we're lucky.

**Comment by HollishKid** [comment]
Thank you very much !

Indeed, you might be right, they might come from an unloaded world.
If they're harmless warns, one single warn in console would suffice =)

thanks alot again, I'll try it out asap

**Comment by HollishKid** [comment]
Thanks again, this worked just fine.
Now only displaying a single WARN msessage in console, making it much more readible! 

It get a new error though ... I'm not sure whether to send it here of to the other mentionned plugin manager, but since he's been off the grid for the past years ... I thought I's try it here.

http://pastebin.com/PdByiPy6

Any thoughts on this?

**Comment by mcmonkey4eva** [comment]
That's something wrong with `Trade v1.0 BETA ver3` :/
it might function better if you toggle `workaround damage` in the config.

If that doesn't fix it, you're going to have to find the other plugin's developer, sorry.

**Comment by HollishKid** [comment]
Thanks, I'll try that!

**Comment by HollishKid** [comment]
I haven't had this error since,

Thanks alot!
