### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by HollishKid** [mcmonkey4eva/Sentinel#30]
Hello!

I get death mesages for every sentinel that dies.
Is there a way to remove them completely?

Thanks!

**Comment by mcmonkey4eva** [comment]
I've added a config option to the latest version for this - `random.death messages` -> set it to `false` to hide the message that appears when a Sentinel dies.

**Comment by HollishKid** [comment]
Great thank you very much =)

**Comment by HollishKid** [comment]
I'm afraid this doesn't seem to be enough for the messages to be removed?
Despite my config being configured as:

    # Whether to permit death messages to show for Sentinel NPC deaths.
    death messages: false

I have filtered for messages not to be sent to console or IG chat with ChatControl, but the messages do still appear on my discord server? https://www.spigotmc.org/resources/discordbot-bukkit-spigot-edition.19717/

Thanks for your insight on this! =)

**Comment by mcmonkey4eva** [comment]
@HollishKid Perhaps you have a plugin announcing deaths separately from the core Mojang-code death announcements? That configuration is tested and confirmed to hide the built-in death messages.

As far as Discord,
that could be the DiscordBot not respecting Sentinel's edit to the events.

Let's bug him about it directly, eh?

@LXGaming DiscordBot should be listening to events with:
`@EventHandler (priority=EventPriority.MONITOR)`
This will ensure it respects other plugins that cancel or modify any given event.

**Comment by LXGaming** [comment]
Thanks for telling me about this, I have changed the EventPriority, Will have new version out soonish

**Comment by LXGaming** [comment]
Update has been pushed to Spigot, Let me know if you have any issues and I shall work to solve them :)

**Comment by HollishKid** [comment]
Thanks to both for helping me out with this!
Very much appreciated =D

I will test this out by tomorrow!
