### ISSUE TITLE
Sentinel's are affected by SKILLapi

### ISSUE THREAD

**Issue by CorporalBruno** [mcmonkey4eva/Sentinel#33]
When you set SKILLapi up on your server, it affects NPCs automatically. For instance, I have a default, group of classes for new players, and Sentinels on that same server are all level 1 wizards, but no tags confirm this that are related to skillapi. The name tag gives it away (npc named &4Orc Warrior is now &f&lWizard &4Orc Warrior). So it may just be affected by the plugin in a way that causes the npcs to have the name card given to players.

**Comment by mcmonkey4eva** [comment]
This sounds like SkillAPI is failing to account for and avoid NPCs?
