### ISSUE TITLE
Suggestion: Speed option

### ISSUE THREAD

**Issue by Crasher545** [mcmonkey4eva/Sentinel#36]
Speed option for define moving speed when sentinel have target. For example set path points /npc path set patrol speed /npc speed 0.7 and set /sentinel speed 1 for speed when sentinel attack target. After target killed npc back to patrol speed 0.7

**Comment by mcmonkey4eva** [comment]
Excellent idea. Will add :)

**Comment by mcmonkey4eva** [comment]
Sorry for taking so long to do this. Added now! :)
