### ISSUE TITLE
Suggestion: Towny targets

### ISSUE THREAD

**Issue by hmmcrunchy** [mcmonkey4eva/Sentinel#37]
Targeting of specific town or nation residents

**Comment by mcmonkey4eva** [comment]
Is Towny still updated?
I can't find a version more recent than 1.8!

**Comment by hmmcrunchy** [comment]
Yes I believe  so, on Palmer games website 

They don't release one every mc version but it still works fine on 1.10

**Comment by Zimoune** [comment]
Latest dev build of towny is available here: [towny repository](http://towny.palmergames.com/file-repo/Towny%20Advanced/Development/0.91.1.5/)

**Comment by Jabelpeeps** [comment]
@hmmcrunchy @Zimoune While you are waiting for mcmonkey to implement this, you could always try my re-write of Sentry:- https://github.com/Jabelpeeps/Sentries which is attempting to maintain the old functions, before adding new ones.  There is a link to the builds on my CI server in the ReadMe.  Let me know how you get on.

**Comment by mcmonkey4eva** [comment]
Towny targets are now available to Towny servers in the latest dev build (#73)
Simple `/sentinel addtarget towny:BADDIE_TOWN`

**Comment by mcmonkey4eva** [comment]
Oh and please do reply telling me how it works for you, and any additional features you'd like to see!
