### ISSUE TITLE
Sentinel's Respawn Time not working or saving

### ISSUE THREAD

**Issue by VenionTC** [mcmonkey4eva/Sentinel#39]
I've been having some trouble setting up Sentinels as I'm trying to give some of them respawn times of half an hour (for which I'm entering 36000 ticks), but when killed the npcs simply respawn in roughly 10-12 seconds and when the server restarts and I do **/sentinel info** their respawn time seems to have reset back to the 100 ticks default.

**Comment by mcmonkey4eva** [comment]
For the first part, it's pretty common to end up having two separate respawn timers running. EG a Citizens core respawn time, or a Denizen respawn time, in addition to the default Sentry one. As for respawn time resetting after restarts, there could be some screwup with the persistence, I'll look into that.

**Comment by VenionTC** [comment]
I tried using plain old **/npc respawn**, but they were still coming back after 10 seconds regardless.

Would this still work - **/npc health --respawndelay 1000s** ?

**Comment by mcmonkey4eva** [comment]
Okay using either of those is entirely wrong. The moment you use the, the respawn engine is borked.
You pretty much have to delete the NPC and start over to avoid that.
Use only the respawn controls available in `/sentinel/` to allow proper respawning.

**Comment by mcmonkey4eva** [comment]
Also I don't see any reason for the respawn time to not save properly, it's saved the exact same as several other things are, through a `long` integer variable through the C2 persistence engine.

**Comment by VenionTC** [comment]
So it appears that the respawn time works fine as long as the npc doesn't have the health trait, but without the health trait they won't run denizen On Death tasks, so I'm in a bit of a bind here.

**Comment by mcmonkey4eva** [comment]
@VenionTC Ah. In that case, er...
`/npc health -s`
I think? Should disable the respawning.

**Comment by VenionTC** [comment]
Just comes up with:
```
Unknown flag: s
/npc health --set # (-r)
```
-r doesn't seem to do anything either

**Comment by mcmonkey4eva** [comment]
Er.... `/npc health --set 20 -s` ? These are really ancient commands :/

**Comment by VenionTC** [comment]
Nah, just gets the Unknown flag thing again.

**Comment by mcmonkey4eva** [comment]
Okay! So. The health command was bugged in Denizen.
Download dev build 606+ of Denizen to fix that: http://ci.mineconomy.org/job/Denizen_Developmental/
And you can then use `/npc health -s` to disable their respawn system.

Also I am able to replicate the value resetting, but I haven't the slightest why it's not persisting `long` values correctly. I'm going to bug @fullwall about it. Hopefully with his help we'll get a fix for that soon as welll :)

**Comment by VenionTC** [comment]
Nice one :) Looking forward to it

**Comment by mcmonkey4eva** [comment]
An update was pushed to Citizens2 and its API to fix the long persistence issue! :)

Can you please update to latest dev build of Citizens2 and confirm the fix?

**Comment by VenionTC** [comment]
Respawn time is now persisting and the `/npc health -s` command works as expected :)
Just out of curiosity, any way to remove the sentry trait from all npcs at once? I get a string of "trait not found" errors when I restart now.

**Comment by mcmonkey4eva** [comment]
I have no idea on that one actually. A find-and-replace in the Citizens saves.yml might do for making it disappear, but I'unno.

**Comment by VenionTC** [comment]
Yeah I could try that, thanks. One last thing I've noticed - sentinel npcs attacked by other sentinel npcs do not seem to retaliate, despite having fightback enabled.

**Comment by mcmonkey4eva** [comment]
Can't replicate that ^ I just made one NPC attack another, and then they both duked it out.
