### ISSUE TITLE
Gamerule keepInventory

### ISSUE THREAD

**Issue by Sprungente** [mcmonkey4eva/Sentinel#41]
Could u change the handle with itemdrops. I wanna use sentinel on a world, they people don't loose his inventory, so i use gamerule keepInventory. Npc's aren't drops with keepInventory. Could u please bypass itemdrops on NPC's? 
for example. A quest with the plugin quests requiere an Item from merlin. Merlin have this Item and the players have to kill him, to get the item.

Hope you can change it :D Thanks u for develope this plugin

**Comment by mcmonkey4eva** [comment]
This is already an option in your config!
Just toggle `workaround drops` near the bottom of your Sentinel config.yml file to `true`.
