### ISSUE TITLE
Help Respawn on death issue

### ISSUE THREAD

**Issue by prowlmaster** [mcmonkey4eva/Sentinel#43]
Ok i ran into an issue on my server

1 Sentinel Respawning
Basically i would create a npc give it the trait sentinel and i would set the respawntime to say 400 ticks or 20seconds but the issue i have is after i kill the sentinel he respawns where he dies at i would like for it to be automatic for the npc to respawn where you first created instead of trying to create multiple Sentinel guards and having to npc copy then type the command /sentinel spawnpoint over and over please fix this add some workaround instead of me creating 20npcs and having to type /sentinel spawnpoint 20 times ~Thanks

**Comment by mcmonkey4eva** [comment]
You want the respawn point to be defaulted differently than it is, in a rather unusual way.
You want like the system to automatically cater to your personal needs, and cause confusion for everyone else.

No.

**Comment by prowlmaster** [comment]
How is that catering to my personal needs Citizens work that way by default where ever you create a npc thats the default spawnpoint of where u created the npc you want to create a spawnpoint command but not have the npc respawn originally where you created it doesnt really make sense to me ok then was just a question

**Comment by mcmonkey4eva** [comment]
... I have no idea what that ramble means, but ... yeah no that's never been a default for Citizens or related. The system works pretty cleverly ATM, and in a reasonably predictable way for the most part, once you know what it's supposed to do. Changing that would be pointless confusion.
