### ISSUE TITLE
sentinels equipped with splash potions throw potions with no effect

### ISSUE THREAD

**Issue by Volkenstein666** [mcmonkey4eva/Sentinel#44]
ALSO - tipped arrows placed in a sentinels inventory using /npc inventory are ignored when a sentinel is equipped with a bow. I will be troubleshooting this a bit today but I'm not surprised about the splash potions not working since spigot has problems with the new data values that potions use- actually I dont know where the problem is

**Comment by mcmonkey4eva** [comment]
Can't replicate this - my Sentinel NPCs are successfully able to take out a cow target with some `Instant Damage` splash potions.

**Comment by mcmonkey4eva** [comment]
Also, an arrow tipped with `Instant Damage II` played the correct effect and rapidly slaughtered cows.
