### ISSUE TITLE
sentinels equipped with specific splash potions revert bac to splash water bottles on server restart

### ISSUE THREAD

**Issue by Volkenstein666** [mcmonkey4eva/Sentinel#45]
I previously had an issue where I thought sentinels equipped with splash potions threw them but no effect was had on their target. The sentinel was standing in a world guard region. By doing /rg flag pvp allow (in world guard) I was able to get the potions to work on their targets. However, and this  I think has more to do with spigot or citizens2 than sentinel - upon server restart the sentinel I had equipped with a splash potion of poison is now holding a splash potion of water. The F is up with these new potion data values or lack thereof not saving whe using spigot. Its not the only place theres a problem - sometimes regenchests (another plugin) I fill with specific splash potions turn into water on server restart. Any ideas for a workaround?

**Comment by mcmonkey4eva** [comment]
first, make sure you're ENTIRELY up to date with all plugins and Spigot itself.
If the issue still occurs, it's a problem within Citizens2. Please report it there: https://github.com/CitizensDev/Citizens2/issues
