### ISSUE TITLE
Npc with respawntime 0 respawn on server restart

### ISSUE THREAD

**Issue by Eredrim** [mcmonkey4eva/Sentinel#48]
All is in the title ;)

----------
Sentinel 0.6
Spigot 1.10.2

**Comment by mcmonkey4eva** [comment]
Are you running Citizens 2.0.20?

**Comment by mcmonkey4eva** [comment]
If you're not, could you please update and re-apply the respawn time setting?

**Comment by Eredrim** [comment]
I updated Citizens to 2.0.20 and the problem persists. (Even if I re-apply respawn time setting)
