### ISSUE TITLE
Spawnpoint doesn't change on npc copy

### ISSUE THREAD

**Issue by Eredrim** [mcmonkey4eva/Sentinel#49]
When I copy npcs (command: /npc copy), the sentinel spawnpoint is not updated.

**Comment by mcmonkey4eva** [comment]
Define updated?

**Comment by Eredrim** [comment]
The spawnpoint stay the same as the npc which was copied. For instance: if I copy the npc A to a new npc B. The npc B spawnpoint equals to the npc A spawnpoint. On server restart, they appear both on the same place.

**Comment by mcmonkey4eva** [comment]
.... yes, what else should it do?

**Comment by Oruss7** [comment]
set spawnpoint on new npc B location ?

**Comment by mcmonkey4eva** [comment]
Spawnpoint is a spawnpoint... if you want it to spawn just wherever it was at, disable the spawnpoint feature.
