### ISSUE TITLE
Sentinal /trait sentinal not working?

### ISSUE THREAD

**Issue by DarthPossom** [mcmonkey4eva/Sentinel#51]
Alright, so I select my npc, then type /trait sentinal, like it says on the website, then it says "couldn't change sentinal: trait not found" any reason why this is?

**Comment by mcmonkey4eva** [comment]
Because you're spelling sentinel wrong.

**Comment by DarthPossom** [comment]
Hahaha, no sorry I was really tired stayed up almost all night didn't catch that typo. I fixed it, had to reload the server. Wasn't thinking straight sorry.
