### ISSUE TITLE
Enhancement: Damage and Death triggers (Denizen Integration)

### ISSUE THREAD

**Issue by Sparclen** [mcmonkey4eva/Sentinel#52]
Sentry added 2 extra NPC triggers to denizen:

- Damage Trigger
- NPCDeath Trigger

This allowed you to easily create more interactive combat NPC's. For example, they'd say 'You'll regret that!' and play a sound when attacked, or they'd grunt, explode or spawn more mobs when they died.

Sentinel is currently lacking this feature and it would be great if this could be added once again.

Thanks for the hard work!

**Comment by mcmonkey4eva** [comment]
Damage is a trigger built in to Denizen.
`NPCDeath` trigger can be replaced by Denizen's health trait and the `on death` action, fully compatible with Sentinel :)
