### ISSUE TITLE
Could not pass event PlayerMoveEvent to Citizens

### ISSUE THREAD

**Issue by Rocologo** [mcmonkey4eva/Sentinel#53]
I'm not sure if this error is related to Sentienel or Citizens? But here you go. 

I have the TARDIS plugin installed on my server, and each time I enter the TARDIS (another world called TimeVortex) I'm getting ALOT of these errors in the console. When I return to the normal world the error disappear  again. 

> [18:42:16] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Citizens v2.0.19-SNAPSHOT (build 1379)
> org.bukkit.event.EventException
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
> 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.IllegalArgumentException: Cannot measure distance between TARDIS_TimeVortex and asgaard
> 	at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.mcmonkey.sentinel.SentinelTrait.onPlayerMovesInRange(SentinelTrait.java:1170) ~[?:?]
> 	at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	... 15 more
> [18:42:29] [Server thread/INFO]: There are 1/10 players online:
> [18:42:29] [Server thread/INFO]: Rocologo
> [18:42:32] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Citizens v2.0.19-SNAPSHOT (build 1379)
> org.bukkit.event.EventException
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:610) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInLook.a(SourceFile:88) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
> 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.IllegalArgumentException: Cannot measure distance between TARDIS_TimeVortex and asgaard
> 	at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	at org.mcmonkey.sentinel.SentinelTrait.onPlayerMovesInRange(SentinelTrait.java:1170) ~[?:?]
> 	at sun.reflect.GeneratedMethodAccessor216.invoke(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-7f9fbe5]
> 	... 15 more

**Comment by mcmonkey4eva** [comment]
Update both Citizens and Sentinel, this bug shouldn't be present in latest builds.

**Comment by Rocologo** [comment]
Yes, this seems to fix the error. Sorry for not checking if there were new updates before making a report.

It would be nice to get some kind of notification. :-)
