### ISSUE TITLE
Problem with snow balls

### ISSUE THREAD

**Issue by Eredrim** [mcmonkey4eva/Sentinel#54]
It doesn't work properly. Snow balls pass through players and they are rarely damaged. This occurs when player don't move or when they move slightly.

**Comment by mcmonkey4eva** [comment]
Are you sure it's movement related, and not connected to, say, the player being really close to the NPC?

**Comment by Eredrim** [comment]
I'm not sure it is caused by movement, it is just an observation. However I am sure I was close to the NPC because it threw snowballs in my direction and I verified the attack range.

**Comment by mcmonkey4eva** [comment]
Should be better on the latest build.

**Comment by Eredrim** [comment]
Hello,
I tried the latest dev build of sentinel and I note the same problem. I attached a short video capture to show you the problem. It was captured in survival and without the /god.
[Minecraft 1.10.2 Snowball issue.zip](https://github.com/mcmonkey4eva/Sentinel/files/417075/Minecraft.1.10.2.Snowball.issue.zip)

**Comment by mcmonkey4eva** [comment]
Can you try that with a less oddly positioned NPC?

**Comment by Eredrim** [comment]
I already tried. Same problem.

**Comment by Eredrim** [comment]
Seems it works correctly with the latest versions of spigot, citizens and sentinel.
