### ISSUE TITLE
[Feature] team target

### ISSUE THREAD

**Issue by Eredrim** [mcmonkey4eva/Sentinel#55]
It would be great to add scoreboards team as targets. For instance, a npc could focus only the blue team.

**Comment by Jabelpeeps** [comment]
@Eredrim While you are waiting for mcmonkey to implement this, you could always try my re-write of Sentry:- https://github.com/Jabelpeeps/Sentries which is attempting to maintain the old functions, before adding new ones.  There is a link to the builds on my CI server in the ReadMe.  Let me know how you get on.

**Comment by mcmonkey4eva** [comment]
Scoreboard team targets are now available to servers in the latest dev build (#76)
Simply `/sentinel addtarget sbteam:BLUE_TEAM`
Also supports ignores!

Oh and please do reply telling me how it works for you, and any additional features you'd like to see!
