### ISSUE TITLE
[Suggestion] Bow accuracy?

### ISSUE THREAD

**Issue by PsychoLynx** [mcmonkey4eva/Sentinel#56]
I was wondering if it might be possible to have an accuracy stat to add some deviation to how accurately Sentinels with bows fire at their targets (in order to have less sniper-like bowmen).

**Comment by mcmonkey4eva** [comment]
Well that's a fun request.
I kept hearing "make them MORE accurate" so much that I added a config option to do that.

Rapid fire bow Sentinel + poor accuracy = the ground is littered with arrows pretty quickly.

I couuullldd add deviation, if you really want that...

**Comment by PsychoLynx** [comment]
Yeah, I would like a state to have a little deviation in the trajectory to not make it as predictable, partially due to the sentries being supposedly "inexperienced" in-game and also to not make them fire the same exact trajectory into a block when a mob might be hiding behind one.

From the end-user point of view, I think a per-sentry stat would be great (So we can have both snipers and noob rangers).

**Comment by PsychoLynx** [comment]
Thank you very much! You rock!
