### ISSUE TITLE
Rabbit NPC won't chase me 

### ISSUE THREAD

**Issue by Stupo564** [mcmonkey4eva/Sentinel#58]
as I said on Spigot my Rabbit NPC won't chase players or monsters. I did everything right. The rabbit deals damage to near players but he won't move (lazy shit =D). But a Player NPC DO chase me but won't deal damage.
I've checked the config but theres nothing wrong. I also changed some stuff but still no difference

**Comment by mcmonkey4eva** [comment]
I'm not sure why, but even after I accounted for all logical issues I could think of, they just kinda... hop in place.

I sent the issue upstream to Citizens: https://github.com/CitizensDev/Citizens2/issues/876

**Comment by Stupo564** [comment]
yea they do! It worked with sentry :/

**Comment by Stupo564** [comment]
ouh they released a new update with a rabbit pathfinding fix <3
Thanks alot for the help :)
I really Appreciated ur help :>

**Comment by mcmonkey4eva** [comment]
Try going into your Citizens config - find the line:
`use-new-finder:`
and set it to  `true`.
Then boot up your server.

Note that your server must be fully stopped at the time you edit the Citizens config because of the odd way the C2 config was designed.

**Comment by Stupo564** [comment]
Yea it works :) Thanks alot for your help :)
