### ISSUE TITLE
NPC path and target event:pvp doesnt work together

### ISSUE THREAD

**Issue by Delfinsko** [mcmonkey4eva/Sentinel#59]
I have a problem, when i create my NPC and traits it with sentinel, i make it go a path with /npc path.... then i add target event:pvp to the npc, but it doesnt seem to work for me.. any help maybe? :)

**Comment by mcmonkey4eva** [comment]
Define "`doesn't work`"?

Are you the person doing the PvP? If so, are you sure you're not on the NPC's ignore list, and are you sure you're a valid target in general (not in creative for example)?

**Comment by Cyborax** [comment]
yes i have the same issue.. if the npc is trait to sentinel and i attack him if its a monster i can attack it. but if the npc --type is player i can attack it but the sentinel dont loose any health. And i trait it with health bevore.
example:
/npc --type spider (get damage)
/npc --type player (get no damage)

**Comment by mcmonkey4eva** [comment]
@Cyborax make sure PvP and related settings are fully allowed for **default (no permissions) players** within the area you're testing.

**Comment by Cyborax** [comment]
i can hit all players and orther player can hit me... but npcs with playerskins cant be attacked.

**Comment by mcmonkey4eva** [comment]
That's really odd. Do you have a plugin (EG: AuthMe, some perms plugins, ...) that will give a player PvP rights that **are not available to default players**?

The short of it is: As long as a Sentinel is not marked invincible, they can take damage so long as a default player can. As that's what they are: default unregistered players.

**Comment by Cyborax** [comment]
hm ok is it possible to give them a monsterbehavior in some case like in sentry?

**Comment by mcmonkey4eva** [comment]
... a what now

**Comment by Cyborax** [comment]
Banana?

**Comment by mcmonkey4eva** [comment]
...
