### ISSUE TITLE
Damage

### ISSUE THREAD

**Issue by ThijsSlop** [mcmonkey4eva/Sentinel#6]
The NPC's can't damage eachother, mobs and players.
How can I fix that?

**Comment by mcmonkey4eva** [comment]
With which weapon(s)?

**Comment by ThijsSlop** [comment]
Every weapon, including hand. I also tried to change the amount of damage but that didn't work.

**Comment by mcmonkey4eva** [comment]
In your config.yml, there is a section that says:
```
    # Whether to use 'workaround' mode of fist damage.
    workaround damage: false
```
Try toggling that?

**Comment by ThijsSlop** [comment]
Yea that worked.
But my NPC does the exact same damage when I have armor on and when I don't have armor on.
That's weird because I set damage to -1

Now my players have to hit my NPC a 100 times with a diamond sword and the NPC is killing the players with 2/3 hits. Armor is also set to -1

**Comment by mcmonkey4eva** [comment]
Oo, I don't think I added backup armor calculations for Sentinel-to-player damage. Will add soon.

**Comment by mcmonkey4eva** [comment]
Tell me if that doesn't work ^ and I'll reopen
