### ISSUE TITLE
/sentinel respawntime

### ISSUE THREAD

**Issue by Cyborax** [mcmonkey4eva/Sentinel#63]
I have an issue that i set /sentinel respawntime for example to 9000 don't work.
i can see the correct value on /sentinel info.
But if i want to test it with /sentinel kill the npc respawns after few seconds.
And the respawntime is in ticks so 9000 should be 450 seconds.

**Comment by mcmonkey4eva** [comment]
Do you perhaps have an alternate respawner enabled?

This is common to accidentally trigger the Citizens (?) or Denizen (health trait) respawn timers.

**Comment by Cyborax** [comment]
yes the npcs are /trait health because i want to use the denizen on death event.

**Comment by mcmonkey4eva** [comment]
You'll have to disable Denizen's respawn timer for the NPC then. Which, I believe, is `/npc health -s`

**Comment by Cyborax** [comment]
ok nice! ill try this

**Comment by mcmonkey4eva** [comment]
Did it fix the problem?

**Comment by Cyborax** [comment]
yes ;) this problem seems to be fixed by using /npc health -s
Thank You
