### ISSUE TITLE
Skeleton NPCs

### ISSUE THREAD

**Issue by mawej1** [mcmonkey4eva/Sentinel#64]
Bug screen: http://imgur.com/oWcLxz4

They also seem to ignore their Sentinel range, as they try to approach the player from 10+ blocks

Save: http://mcmonkey.org/paste/35292

**Comment by mcmonkey4eva** [comment]
That looks like two NPCs somehow got tangled up in each other or something weird.

I don't even know. Looks like a Citizens pathfinding screwup.

Also, note that there is a 'chaseRange' in addition to a standard 'range'

**Comment by mcmonkey4eva** [comment]
Deferring to Citizens issue page for now.
