### ISSUE TITLE
No player damage

### ISSUE THREAD

**Issue by TheConsciousness** [mcmonkey4eva/Sentinel#67]
Maybe I have it misconfigured, but my sentinels who are range-attacking myself (OWNER) are doing no damage. I can take damage from everything else, and the sentinels can damage mobs...just not me. What could I be missing?

**Comment by mcmonkey4eva** [comment]
Are you sure:
- PvP is fully enabled for the NPC and yourself
- You are not on the NPC's ignore list (`/sentinel removeignore owner`)
