### ISSUE TITLE
Drop Percentages

### ISSUE THREAD

**Issue by Venlious** [mcmonkey4eva/Sentinel#69]
Able to configure a percentage for the drops to drop when a Sentinel NPC is killed. If it were only possible in the config, that'd already do good.

**Example:**
            `  type: PAPER`
            `  amount: 6`
            `  durability: 0`
            `  drop-chance: .5 #Equals 50% drop chance`
            `  mdata: 0`
            `  meta:`
              `    repaircost: 0`

**Comment by mcmonkey4eva** [comment]
You can use **Denizen** to configure advanced settings like drop chances for your Sentinel NPCs.
http://wiki.citizensnpcs.co/Denizen

**Comment by mcmonkey4eva** [comment]
Here's a sample Denizen config for that:
```
myDropChanger:
    type: world
    events:
        on npc death:
        - if !<npc.has_flag[paper_drop]> queue clear
        - random:
          - narrate "Better luck next time!"
          - drop paper quantity:6
```

**Comment by SoraShiunin** [comment]
Coming back to this since its been quite a while.
How would one do this with custom items with lore,nbt tags....

Could a command be created to facilitate this? Or allow PhatLoots?

**Comment by SXRWahrheit** [comment]
Please leave closed github issues in peace. If you need help using the plugin, join us on the Denizen and Citizens Discord:

https://discord.gg/Q6pZGSR

**Comment by mcmonkey4eva** [comment]
Denizen fully supports more advanced items (lore + nbt + etc) as well as executing external commands if needed. If you visit the discord link @SXRWahrheit posted we can help you get started (or view documentation at https://one.denizenscript.com/denizen/logs/ )
