### ISSUE TITLE
Support Crackshot

### ISSUE THREAD

**Issue by madogdog** [mcmonkey4eva/Sentinel#71]
This would make this plugin the best plugin ever! Crackshot is a customizable weapons plugin with endless possibilities. From guns to jetpacks Crackshot has it all! Sadly sentinels just punch me with an ak-47 instead of firing it. https://dev.bukkit.org/bukkit-plugins/crackshot/here's a link if you need it. Here's my idea of how you could do this.

Name a bow what you want the gun to be. Then, when the sentinel pulls back the bow instead of using the bow it uses the gun! It's just a theory Idk if it will work but this feature would be EPIC to add!!

**Comment by MrZybez** [comment]
I agree.  If possible this would be awesome.  I would be willing to throw down some money to make this feature happen.  I have been trying to make a Halo Minecraft RPG and a Military Minecraft Server for a LONG time and all im missing is this feature. Having this compatibility would open Minecraft Servers up from just being medieval to Modern as well.

**Comment by Dragon12dk** [comment]
Would be amazing to see, currently ive got guards that hit people with M16's It would be awesome to see them shoot it!

**Comment by mcmonkey4eva** [comment]
Hey there! I was thinking about starting this, but I noticed the download link provided in the opening post is from 2 years ago - is there a more up to date version I should be using?

**Comment by mcmonkey4eva** [comment]
Added support for that particularly 2015 version of Crackshot. If there's another version that doesn't work with it, lemme know!

**Comment by CollectAndroid** [comment]
Can someone help me? Whenever i equip a NPC with a Gun, it isnt following the player anymore :c, but i want it to still follow the player when the player gets out of a certain range... is that somehow possible?

**Comment by mcmonkey4eva** [comment]
@CollectAndroid that should work fine ... like, just by default? The weapon doesn't influence follow mode...

**Comment by CollectAndroid** [comment]
@mcmonkey4eva okay thanks :D I'm new to this and didn't found anything in the internet... :) I love the plugin, great work! ;D

**Comment by CollectAndroid** [comment]
Huh, I'm still having issues :c where can I activate follow mode? Because the NPC is following me when he has a sword or bow, but not with a gun :/

**Comment by mcmonkey4eva** [comment]
...
Wait, by follow do you mean _chasing you down to attack you_?
That's different.
`/npc chaseranged`

**Comment by CollectAndroid** [comment]
Still the same problem :C if i equip the NPC with a gun, it never moves, and it never shoots in the direction of the player, it just shoots in the direction its looking at. It works perfect with bows and swords, but in my case i need the NPC to use a gun (Stormtroopers with Bows don't look good + i made some 3D Models and it would be awesome if my gamemode could have that feature too :D)

**Comment by mcmonkey4eva** [comment]
That should be fixed in the dev builds http://ci.citizensnpcs.co/job/Sentinel/

**Comment by CollectAndroid** [comment]
Okay thank you, now that is working c:
But the next issue i'm having is that if i create a Path for the NPC and equip it with a gun, it wont leave the path when he gets hit by a player comes, he tries to shoot but he is still forced to follow the given path. Is it possible to make him like he has a normal sword (Follows the path, when a player attacks him he follows the player and then when the player is dead he goes back to his path?)

**Comment by mcmonkey4eva** [comment]
Oooo you know what, I don't think I properly enabled chaseranged for guns. Can you open a new issue about that?

**Comment by CollectAndroid** [comment]
Okay i did.
