### ISSUE TITLE
Followclose, AI improvements, and fightback stupidity

### ISSUE THREAD

**Issue by brooklynstarr** [mcmonkey4eva/Sentinel#75]
Hi,

Sentry had a useful feature to determine how close a Sentinel could follow the person they were guarding. This prevented the npc from being in your face whenever you are busy building, and allowed us to set the targeting radius. I don't know if it's related, but Sentinels also seem to not understand when to attack and when to return to the person they are guarding; this may be an AI thing, but it prevents them from being effective as they keep turning back to guard instead of killing the mob.

Also, when fightback is enabled, if you accidentally hit the sentinel that is guarding you, they will strike you then begin hitting themselves until they die. This is stupid, sentries never did this because they automatically set the person they were guarding as non-targets, and doing addignore:player will make you vulnerable to other players. I understand you can manually add your own username as an ignore target, but should we, considering it's guarding us? This would also help when having to recreate all the Denizen scripts that were broken by moving to this plugin.

Thanks.

**Comment by mcmonkey4eva** [comment]
So I've proooooobably fixed them attacking themselves.

The NPC guard target radius is the existing radius options, no need for additional config there.
I set the follow radius to be several blocks back to allow easy building without issue. I could make it configurable if needed...

**Comment by brooklynstarr** [comment]
Thank you, sir! I will check it out.
