### ISSUE TITLE
Sentinel Navigation is not updating opponent's location

### ISSUE THREAD

**Issue by Mwthorn** [mcmonkey4eva/Sentinel#76]
Whenever a Sentinel targets another an NPC. They navigation does not update their target's location. Their navigation only updates when they finished their previous navigation.
However, once they are in close range, things turn out quite okay with their combat. When they detect each other in long distances, their navigation to each's position is not updated. (Kinda looks like Juist)
I've tried to change the config to make them update faster but does not seem to work.

Gif showing the issue. (Focus should be the 2 npcs that are provoked)
https://gyazo.com/893e46c489f8fad3ff55fe330896f735

Citizens Version: Build 1409
Citizens config: http://mcmonkey.org/haste/35559
Sentinel Version: Build 58
Sentinel Config: http://mcmonkey.org/haste/35560

**Comment by mcmonkey4eva** [comment]
I don't see what's going on in that GIF at all 0.o
The navigation should accurately update every half-second or so to target the correct enemy...

**Comment by Mwthorn** [comment]
Recorded a video to try and show it more detailed. Its about the NPCs target-navigation I wanted to focus on.
https://youtu.be/3AWqE3avawM

**Comment by mcmonkey4eva** [comment]
Is that still happening in the present version?

**Comment by Mwthorn** [comment]
Nope. Updated Denizen, Sentinel and Citizen and things seems to be working well now.
