### ISSUE TITLE
War integration

### ISSUE THREAD

**Issue by Lufou** [mcmonkey4eva/Sentinel#78]
I have just seen that Sentinel doesn't have War integration such as Sentry.

Could you add it please ? (npc target ennemy team)

THX

**Comment by mcmonkey4eva** [comment]
Throw your support in for https://github.com/mcmonkey4eva/Sentinel/issues/65

**Comment by Jabelpeeps** [comment]
@Lufou While you are waiting for mcmonkey to implement this, you could always try my re-write of Sentry:- https://github.com/Jabelpeeps/Sentries which is attempting to maintain the old functions, before adding new ones.  There is a link to the builds on my CI server in the ReadMe.  Let me know how you get on.
