### ISSUE TITLE
Respawntime + spawnpoint not working

### ISSUE THREAD

**Issue by xXMrGXx** [mcmonkey4eva/Sentinel#79]
1.The Sentinel NPCs ignore their Respawntime
2. The Sentinel NPCs respawn at their death point, not at their spawnpoint

**Comment by mcmonkey4eva** [comment]
You likely have an external plugin influencing respawns.

A common cause is Denizen - if you have that installed, make sure the `health` trait is either not on the NPC or not set to cause custom respawning.

Citizens itself can also do this somewhere, make sure you don't have any respawn-related commands in use other than the Sentinel one.
