### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by ThijsSlop** [mcmonkey4eva/Sentinel#8]
1. Can you add a spawnpoint for the NPCs, so if they get killed, they respawn at the location I want them to respawn. (configurable for every single NPC)
2. If the NPC damages a player, the player will be knocked back like real player PVP
Thank you in advance.

**Comment by mcmonkey4eva** [comment]
`If the NPC damages a player, the player will be knocked back like real player PVP Thank you in advance.` Oh yeah I forgot to replicate that for workaround damage mode. It already works for non-workaround damage >.>
