### ISSUE TITLE
Retaliation in groups request

### ISSUE THREAD

**Issue by Azfaloth** [mcmonkey4eva/Sentinel#80]
Would it be possible to assign a "group number" variable to a sentinel? So that if the particular sentinel was attacked, all the sentinels belonging to the same group number would attack the attacker.

Like an extension of the retaliation feature except instead of just the single NPC retaliating, the whole group(NPCs with the same group number) targets the entity that attacked one of them.

Please let me know if this is already possible in some other way.

Thank you for your amazing plugin.

**Comment by mcmonkey4eva** [comment]
So... basically, NPC ZombiePigmen! I can add that.

**Comment by mcmonkey4eva** [comment]
Added to dev build 63 :)
