### ISSUE TITLE
Problem With Sentry Importer

### ISSUE THREAD

**Issue by keeganjohn** [mcmonkey4eva/Sentinel#82]
I am having a major problem with the sentry importer. My server is currently in 1.10, and when i run the command it says 0 sentries imported. I figured that since sentry didn't work with 1.10, that might be the problem, so i tried it in a 1.9 server instead. When i did it on that server, i was completely unable to get sentinel to respond to any command, and got a tonne of errors whenever i tried to use anything related to it. So i decided to go down again, and try 1.8. In 1.8, i was able to access the sentinel menu, and sentry was working, but when i ran /sentinel sentryimport, it said it started, and then i got a huge thing of error messages, and it never finished. I'm using the newest version of sentinel and sentry, and citizens build 1419. Please Help!

**Comment by mcmonkey4eva** [comment]
Use an old version of Sentinel for 1.9.4 for that to work.

**Comment by keeganjohn** [comment]
would that version be .5 b37?

**Comment by keeganjohn** [comment]
I tried replacing Sentinel with version 0.5 while on the 1.10 server, that produced the same "Imported 0 Sentries" thing. If i need to do it on a 1.9.4 server, i would appreciate some help because i cant seem to find the right version of Citizens for 1.9.4

**Comment by mcmonkey4eva** [comment]
Yeah 1.9.4 - http://wiki.citizensnpcs.co/Versions

**Comment by keeganjohn** [comment]
same error, 0 sentries. Running on Craftbukkit 1.9.4-R0.1, The citizens you referenced, The newest available sentry (v1.9.1), and sentinel build 37.

**Comment by keeganjohn** [comment]
wait i may have forgotten to copy the citizens folder on that last attempt. Sorry let me check

**Comment by keeganjohn** [comment]
ok, that appears to have worked, for the most part. It looks like it completley eliminated the paths that they had set up for them, but i think that is controlled through citizens. Although i believe that the paths were working before this.

**Comment by keeganjohn** [comment]
i just checked with my original file, it appears that importing removes the paths of the NPC's. I'm not sure if you were already aware of that.

**Comment by mcmonkey4eva** [comment]
That's odd. Shouuuuuuuuuulllddnnnn'''tt do that, with a glance at the relevant code there's no mention of path points.

**Comment by keeganjohn** [comment]
i'll do it again, just to make sure it wasn't a fluke or anything like that

**Comment by keeganjohn** [comment]
nope, removed every path of all the NPC's

**Comment by keeganjohn** [comment]
well, it probably didnt remove the paths of NPC's that wern't sentries, but i didnt have any of those with paths

**Comment by mcmonkey4eva** [comment]
Don't know what to tell you, that's not something in the import code touches.

**Comment by frackandx** [comment]
hei can you tellme how to import it? because i still cant import it say imported 0 sentry npc

**Comment by frackandx** [comment]
im at 1.10
