### ISSUE TITLE
After a fight, sentinel don't go back to standing point

### ISSUE THREAD

**Issue by MorenaDaniel** [mcmonkey4eva/Sentinel#85]
Hi ! My issue is that, everytime my NPC go in a fight, he don't go back to where i placed it.
I place my npc by using "/npc move", and when a zombie spawn next to the guard, he run and kill then stop where he killed the zombie. How can i make him return bakc to my "/npc move" point ? Thanks 

EDIT: After using /Npc path the npc go back to his starting point, but he don't keep the good angle, and just face the wall :/

**Comment by mcmonkey4eva** [comment]
That's fairly inevitable, the NPC will face the direction they walked in by default.

You do have options.
One is `/npc lookclose` to make them automatically look at nearby players while idle.
Another is a quick Denizen script ( https://wiki.citizensnpcs.co/Denizen ) using the `look` command to make it face a certain way.
