### ISSUE TITLE
Sentinels do not return to player they are guarding after world change

### ISSUE THREAD

**Issue by ssamjh** [mcmonkey4eva/Sentinel#87]
When i create a NPC, set it as my guard then leave the world, it will not come back to my when I teleport back.

Using version 0.6 on Spigot git-Spigot-850da7e-b5fb9a1 (MC: 1.10.2)
Citizens: v2.0.20

**Comment by mcmonkey4eva** [comment]
Is this replicable on latest dev build? http://ci.citizensnpcs.co/job/Sentinel/ it should teleport to you if you change world.
