### ISSUE TITLE
Sentinels Do not attack!

### ISSUE THREAD

**Issue by DestinysProphet** [mcmonkey4eva/Sentinel#90]
Hello, i have been trying numerous times to get the Sentinel to attack but it just won't. I have done /sentinel addtarget OWNER, PLAYER and i did /sentinel addtarget event:pvp and pve. Nothing works please help. Also, how can i set the respawn time for sentinels?

**Comment by mcmonkey4eva** [comment]
Did you `/sentinel removeignore owner`? It defaults to not attacking its owner.

**Comment by DestinysProphet** [comment]
Oh no i didn't Thank you! Also, what about the other question?

**Comment by mcmonkey4eva** [comment]
`/sentinel respawntime TIME - Changes the time it takes for the NPC to respawn, in ticks.`

**Comment by DestinysProphet** [comment]
Ok. Thank You!
