### ISSUE TITLE
Bug targettime

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#93]
Hello,

You can watch this short video to see the bug : https://streamable.com/37lg

When a sentinel targets you, and then loses you, it does not come back to its original place, even though the citizen "npc path" should command it to do so. Furthermore, as you can see at the middle of the video, the sentinel who forgots about you because of a "targettime" option does not come back to its place, and becomes completely inactive : it does not attack the player anymore, even though it should as you can see at the end of the video (the other NPC (which is a copy) attacks on sight). This is a big issue as a sentinel can stay forever at a place that is not its own if the player "drives" it to this place : it will then never come back (untill next restart).

Also, please note that the "targettime" does not appear in the "sentinel info" display, thus making it impossible to know, in game, how much target time a sentinel has. In addition, in the description of the target time in /sentinel help, you forgot to mention that the time was in ticks, which can lead to some confusion.

Could you please fix the bug, thanks.

**Comment by mcmonkey4eva** [comment]
Give it a maximum chase range that's higher than its pathfinding range; it looks like it just went too far from base and couldn't navigate home anymore.

**Comment by Blamo27** [comment]
As you can see at the start of the video, the maximum chase range is set to 100, which is very high. The same problem occured when we set it to 1000. What do you think we should do on that matter ?

**Comment by mcmonkey4eva** [comment]
Oh, typo, sorry. LOWER* than its pathfinding range.

**Comment by Blamo27** [comment]
When we set it to something lower it simply completely ignores anything that happens past the maximum chase range. Any attack that comes from outside this range is ignored, close combat or ranged, even though we enabled chaseclose and chaseranged.

Video : https://streamable.com/2csw

**Comment by mcmonkey4eva** [comment]
chase range is how far it'll run out to chase an enemy from its home base point.

To flip it around, instead of setting the chase range low, set the pathrange high perhaps?

**Comment by Blamo27** [comment]
It seems to have fixed the bug indeed ! Now the NPC correctly reacts to long-distance attack. Now that this is working, however, we couldn't help but notice there was some issues with the general way the pathfinding seems to work...

Video : https://streamable.com/pden
(at the beggining the player just fired an arrow at the NPC, and waited...)

(that kind of bug happens even when we set the pathfinding back as the way it was before, so it seems to be a general bug)
(at the beggining I just fired an arrow at the NPC)

**Comment by Blamo27** [comment]
Another example (once again the player fired an arrow at the beggining) :
https://streamable.com/5m83

**Comment by mcmonkey4eva** [comment]
Haha RIP that NPC.
That's a Citizens limitation, it has nothing to do with Sentinel specifically.

Try removing the slabs or placing barriers above them so the NPC knows not to or simple can't go there.
Also try fiddling pathfinding-related options in the Citizens config file.

Can't figure it out, open an issue on the Citizens2 page and we'll discuss it there.

**Comment by Blamo27** [comment]
@mcmonkey4eva Well, that's odd, because before, when we used Sentry, the pathfinding seemed to work a lot better... As you can see on this video : https://streamable.com/9e0v

**Comment by mcmonkey4eva** [comment]
chance/luck/positioning/... - Sentinel and Sentry do not define their own pathfinding. They use Citizens for that.

**Comment by Blamo27** [comment]
I'm sorry but I seriously doubt that's just luck... There is something completely buggy here, that wasn't there before... Do you think this is due to a Citizen update ?
Video : https://streamable.com/xgir

**Comment by mcmonkey4eva** [comment]
It's very possible a Citizens or Minecraft updated messed with pathfinding. Have you looked in the Citizens config? There are several related settings that may help...
