### ISSUE TITLE
Bug invincible

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#94]
Video : https://streamable.com/ly4w

There is an issue with some of our NPCs : it appears that some can never die, and some can, and we don't know why. This is the config of both NPCs as shown in the save.yml of Citizen :

For the first one : http://pastebin.com/w6CQwan0
For the second one : http://pastebin.com/PqAWf0c9

**Comment by mcmonkey4eva** [comment]
Really?
You have an external plugin blocking PvP... just look at the message you got from it 0.o

**Comment by Blamo27** [comment]
Nah that's a world guard message, it has no consequence. You can see that since the second one dies even though there is the same message. We can record the video without the world guard region if you want, but as I said it has no effect (if the PVP was indeed blocked, by the way, we should not be able damage the NPCs).

**Comment by mcmonkey4eva** [comment]
Oh.  You also have armor at 2.0, IE delete all damage, and then do it again.
Perhaps lower that to a valid value :P

**Comment by Blamo27** [comment]
You're right, the armor was the issue, when they have 0 armor it's working fine. I think you should indicate that in the description of the armor parameter, as we were far to imagine it worked that way : with Sentry, each point of armor was just one less damage point taken by the NPC. This is quite an issue when you import : we have hundreds of NPC which have an armor value superior to one. We will deal with it now, however. Thanks.
