### ISSUE TITLE
Random item droping

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#96]
We're not sure if this is an issue, but we have a problem : NPCs sometimes drop items, sometimes they don't, sometimes they only drop some. We don't know how to prevent them from dropping anything, as we didn't see any parameter to do that in the /sentinel help.

**Comment by mcmonkey4eva** [comment]
Sentinel doesn't drop anything by default unless configured to via `/sentinel drops`, or via Citizens itself or semirelated plugin inducing custom drops.

**Comment by Blamo27** [comment]
It was indeed one of our plugin : there seems to be an incompatibilty. However we think we found a way to not use that plugin anymore, so it will probably be fine. Thank you.
