### ISSUE TITLE
Ignoring targets doesn't prevent damage from them

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#97]
Hello,

On our server, we used to use the Sentry system of ignored targets to prevent these targets from attacking certain NPCs. For instance, we have guards that we don't want players to be able to kill, but those guards must be killable by monsters when they fight monsters. To achieve that result, we used to add "monsters" as target, and "players" as ignored.
This way, the guards not only ignored the players, but the players weren't able to attack them as well. It seems that this isn't possible anymore : your current system of ignoring targets doesn't prevent these targets from attacking the NPC.

As a result, not only we can't have this RPG-like system of guards you can't attack anymore, but there are also other unwanted effects : previously, when we put up archers on a location, we configured those Archers to ignore other NPCs, so their arrows wouldn't be able to damage their allied NPCs.
Now, Archers can damage and sometimes kill other NPCs from their "team", which is a huge issue regarding Quests : when you have to kill certain NPCs, the archer sometimes kill the NPC you have to kill, thus forcing you to wait for respawn.

Also, on an unrelated topic, we would like to know what is a NPC "Squad".

Thanks.

**Comment by mcmonkey4eva** [comment]
For the main question: make sure `safeshot` is enabled for the NPCs. That makes them never damage an ignored entity, in theory.

A squad is basically: if they trigger one member of a squad, then all members of the squad will fight the target.

**Comment by Blamo27** [comment]
Sorry for the delay. So, safeshot is indeed useful to prevent the second issue I talked about (archers killing other NPCs), but not the first one : players can kill guards who are ignoring them, in the middle of a town for example.

**Comment by mcmonkey4eva** [comment]
Oh.
Well.
Yeah.
That'd happen.
Don't have your guards on ignore mode for the type of bastard that'd do that.

**Comment by Blamo27** [comment]
._. But we don't want players to break roleplay by exterminating the guards in the town ! We can't make them invincible or too strong, also, because they have to actually fight against monsters, not just kill them without taking damage or one-shot them. Can't you make an option or something so a NPC can't be hurt by its ignored targets ?

**Comment by mcmonkey4eva** [comment]
I suppose I could add a config option for it.

**Comment by mcmonkey4eva** [comment]
Yup, simple enough to do. Added precisely that to dev build 75.

**Comment by Blamo27** [comment]
@mcmonkey4eva 
Thanks, it works, however only for close combat. Ranged attacks still damage sentinels who ignore you.
If you could fix that, that would be all for this issue.

**Comment by mcmonkey4eva** [comment]
Oh woops, newest build fixes that too.

**Comment by Blamo27** [comment]
@mcmonkey4eva I didn't test it until now, but it's actually still buggy with bows, even with the latest build.

**Comment by mcmonkey4eva** [comment]
Oops, I made a typo. Hard to find these things when it's difficult to even test the results... sorry about that.
Should be fixed in latest build, I think!

**Comment by Blamo27** [comment]
Seems to work fine now, thanks.
