### ISSUE TITLE
Combo fly

### ISSUE THREAD

**Issue by Blamo27** [mcmonkey4eva/Sentinel#98]
Hello,

As you can see on this video : https://streamable.com/yq9v

Hitting a NPC that ignores you against a wall makes him "fly" (probably by blocking him in the blocks ?). This is also the case when you spam a NPC of arrows and he can't run to you.

Thanks.

**Comment by mcmonkey4eva** [comment]
That looks like gravity was disabled?

**Comment by Blamo27** [comment]
Sorry for the delay. Gravity is enabled.
Also, they only "fly" when they are pushed against a wall.

**Comment by mcmonkey4eva** [comment]
Cannot replicate this at all. Perhaps another plugin is causing it?

**Comment by Blamo27** [comment]
@mcmonkey4eva It seems to be fixed in Minecraft 1.11, will keep you updated if it happens again.
